const allDashboardData = {
    "Geral": {
        totalPending: 0,
        totalDelivered: 0,
        totalOverall: 0,
        drivers: [
        ]
    },
    "APG -GO": {
        totalPending: 646,
        totalDelivered: 221,
        totalOverall: 867,
        drivers: [
            { name: "MEI CARRO - KETHELLEN KAROLAYNE B. DO NASCIMENTO", pending: 2, delivered: 88 },
            { name: "MEI CARRO - Luiz Alberto Bueno da Silva", pending: 0, delivered: 60 },
            { name: "TAC CARRO - MILUQUINO COSTA PINTO JUNIOR", pending: 47, delivered: 31 },
            { name: "TAC CARRO - SAMUEL MARTINS FERREIRA", pending: 69, delivered: 23 },
            { name: "TAC CARRO - MICHELE DA COSTA REZENDE", pending: 48, delivered: 12 },
            { name: "TAC CARRO - ALMI COSTA SOUZA", pending: 66, delivered: 5 },
            { name: "TAC CARRO - VITOR HUGO GONCALVES FALEIRO", pending: 106, delivered: 1 },
            { name: "MEI CARRO - SANTHIAGO CANDIDO SILVA ALVES", pending: 57, delivered: 1 },
            { name: "MEI CARRO - MATHEUS SAMPAIO DOS SANTOS", pending: 99, delivered: 0 },
            { name: "MEI CARRO - VINICIUS JUNIO DE MENDONCA", pending: 74, delivered: 0 },
            { name: "MEI CARRO - RICHARD DAMACENA DE OLIVEIRA", pending: 1, delivered: 0 },
            { name: "CARRO TAC - JAIME XISTO DE SANTANA", pending: 77, delivered: 0 },
            { name: "AQD -MS", pending: 198, delivered: 109 },
            { name: "MEI MOTO AQD JANSLIEL LEAO DA SILVA", pending: 109, delivered: 96 },
            { name: "MEI CARRO AQD FERNANDO DA SILVA BARBOSA OLIVEIRA", pending: 70, delivered: 12 },
            { name: "TAC CARRO AQD GENILTON NOGUEIRA", pending: 19, delivered: 1 },
            { name: "ARI -MT", pending: 425, delivered: 46 },
            { name: "TAC CARRO ARI  CARLOS DANIEL CARDOSO", pending: 108, delivered: 25 },
            { name: "TAC CARRO ARI MYCAELLA LORENA DA COSTA NUNES", pending: 2, delivered: 19 },
            { name: "TAC CARRO ARI POLYANA OLIVEIRA PRADO", pending: 3, delivered: 2 },
            { name: "TAC CARRO ARI TIAGO DE SOUZA LUCENA", pending: 163, delivered: 0 },
            { name: "MEI CARRO ARI GENIVALDO CARLOS VIEIRA", pending: 149, delivered: 0 },
            { name: "ARQ -RO", pending: 2622, delivered: 282 },
            { name: "MEI CARRO ELIZA LOPES DALLA COSTA", pending: 833, delivered: 78 },
            { name: "TAC CARRO WERLES DA SILVA CANDIDO", pending: 66, delivered: 57 },
            { name: "MEI CARRO LUCAS SILVA PEREIRA DOS SANTOS", pending: 191, delivered: 48 },
            { name: "TAC CARRO ANA CAROLINA DIEDRICH DE ALMEIDA", pending: 70, delivered: 48 },
            { name: "MEI CARRO THIAGO DE PAULA SILVA", pending: 334, delivered: 40 },
            { name: "TAC CARRO WELLITON FERREIRA ALMEIDA", pending: 62, delivered: 7 },
            { name: "TAC CARRO ROSIVALDO MARINHO DE ANDRADE", pending: 7, delivered: 1 },
            { name: "TAC CARRO JOSE MARCIO SANTOS", pending: 70, delivered: 1 },
            { name: "TAC CARRO RENAN DE CARVALHO RIBEIRO", pending: 0, delivered: 1 },
            { name: "TAC CARRO BRUNO GABRIEL DE SOUZA PIRES", pending: 68, delivered: 1 },
            { name: "MEI CARRO EDMAR APARECIDO COSTA", pending: 29, delivered: 0 },
            { name: "MEI CARRO DHIONES RIKER OLIVEIRA", pending: 464, delivered: 0 },
            { name: "TAC CARRO CARLOS CALDEIRA LORENZETTI", pending: 21, delivered: 0 },
            { name: "TAC CARRO EDVALDO OLIVEIRA AUGUSTO", pending: 50, delivered: 0 },
            { name: "MEI CARRO VALDECI MORAES JUNIOR", pending: 220, delivered: 0 },
            { name: "TAC CARRO EZEQUIEL SILVA SANTOS", pending: 2, delivered: 0 },
            { name: "MEI CARRO ANA PAULA DA SILVA FERREIRA", pending: 87, delivered: 0 },
            { name: "TAC CARRO GLEICIANE FERREIRA TORRES DO PRADO", pending: 45, delivered: 0 },
            { name: "MEI CARRO MARCELO HELMER NATALI", pending: 3, delivered: 0 },
            { name: "ATF -MT", pending: 11, delivered: 22 },
            { name: "TAC MOTO ATF GUILHERME DE ALMEIDA MOREIRA", pending: 0, delivered: 18 },
            { name: "TAC CARRO ATF ADEMILTON ROFRIGUES DE SOUZA", pending: 0, delivered: 2 },
            { name: "TAC CARRO ATF ALESSANDRA KRETSCHMER", pending: 0, delivered: 1 },
            { name: "TAC CARRO ATF CHARLES ALEXANDRE LOURENÇO", pending: 0, delivered: 1 },
            { name: "TAC MOTO ATF JOELSON CASTILHO DE SOUZA", pending: 9, delivered: 0 },
            { name: "TAC CARRO ATF EDGAR DE MEDEIROS ROCHA", pending: 2, delivered: 0 },
            { name: "BGA -MT", pending: 303, delivered: 31 },
            { name: "TAC CARRO BGA LARYSSA DE OLIVEIRA ROSA", pending: 80, delivered: 23 },
            { name: "TAC CARRO BGA JOSE EUSTAQUIO FERREIRA", pending: 79, delivered: 5 },
            { name: "MEI MOTO BGA ROBERTO PIRES DA SILVA", pending: 1, delivered: 2 },
            { name: "TAC CARRO BGA ANDRE LEAL DE AQUINO", pending: 0, delivered: 1 },
            { name: "TAC MOTO BGA MATHEUS KAUAN RODRIGUES VITOR", pending: 34, delivered: 0 },
            { name: "TAC MOTO BGA GEOVANA RODRIGUES SATURNINO", pending: 109, delivered: 0 },
            { name: "BSB -DF", pending: 921, delivered: 950 },
            { name: "MEI CARRO - NELSON CORDEIRO DE ARAUJO JUNIOR", pending: 74, delivered: 119 },
            { name: "TAC CARRO - CLOVIS RAMALHO PEREIRA", pending: 0, delivered: 96 },
            { name: "MEI CARRO - JOSIMAR DANIEL DOMINGOS", pending: 4, delivered: 75 },
            { name: "TAC CARRO - ELEN SORAYA DE OLIVEIRA CARDOSO", pending: 6, delivered: 62 },
            { name: "TAC CARRO - WELERSON RIBEIRO DOS SANTOS", pending: 44, delivered: 57 },
            { name: "MEI CARRO - ELIDA FERREIRA MAIA", pending: 48, delivered: 55 },
            { name: "MEI CARRO - WEVERSON DOS SANTOS FERREIRA", pending: 50, delivered: 51 },
            { name: "TAC CARRO - GABRIEL DOS SANTOS COUTO", pending: 143, delivered: 50 },
            { name: "TAC CARRO - JOSE COELHO ROCHA FILHO", pending: 31, delivered: 49 },
            { name: "TAC CARRO - WALLYSON MICHAEL GONCALVES DA ROCHA", pending: 23, delivered: 47 },
            { name: "TAC CARRO - GEOVAN NUNES RODRIGUES", pending: 14, delivered: 45 },
            { name: "TAC MOTO - JAIR DO CARMO TOLEDO", pending: 49, delivered: 44 },
            { name: "TAC CARRO - JOAO SANTANA GUERRA NETO", pending: 74, delivered: 38 },
            { name: "MEI CARRO - MICAEL PEREIRA DE MELO SILVA", pending: 0, delivered: 37 },
            { name: "MEI CARRO - DALMISON ALVES DE SOUZA", pending: 58, delivered: 36 },
            { name: "MEI CARRO - GILSON LOPES DE SOUZA", pending: 123, delivered: 34 },
            { name: "MEI CARRO - ROGERIO DE ARAUJO BENIGNO", pending: 94, delivered: 28 },
            { name: "TAC CARRO - REGINALDO DA SILVA ROCHA", pending: 82, delivered: 27 },
            { name: "MEI CARRO - ANDRE GUSTAVO LIRA DOS SANTOS", pending: 4, delivered: 0 }
        ]
    },
    "CAN -GO": {
        totalPending: 971,
        totalDelivered: 49,
        totalOverall: 1020,
        drivers: [
            { name: "TAC MOTO - ELIZANDRO CAUA SILVA OLIVEIRA", pending: 79, delivered: 48 },
            { name: "TAC CARRO - PEDRO HENRIQUE MARQUES DE PAULA", pending: 124, delivered: 1 },
            { name: "MEI CARRO - ALFREDO JUNIO MARTINS DA SILVA", pending: 162, delivered: 0 },
            { name: "TAC CARRO - PAULO DE DEUS MARCELO", pending: 117, delivered: 0 },
            { name: "TAC CARRO - ALEX DIAS DA SILVA", pending: 127, delivered: 0 },
            { name: "TAC CARRO -  ADRIANO RIEIRO DA PAIXÃO", pending: 6, delivered: 0 },
            { name: "TAC CARRO - VIVIANI SAIARA DE SOUZA", pending: 162, delivered: 0 },
            { name: "TAC CARRO - CARLOS RENATO ALVES PEDROSO SOARES", pending: 176, delivered: 0 },
            { name: "TAC CARRO - DOUGLAS DE MOURA GOMIDES", pending: 18, delivered: 0 },
            { name: "CCR -MT", pending: 411, delivered: 205 },
            { name: "TAC CARRO CCR RONILSON CELESTE DUARTE DE SOUZA", pending: 47, delivered: 103 },
            { name: "TAC CARRO CCR MARCELO DELUQUI DA SILVA", pending: 125, delivered: 48 },
            { name: "TAC CARRO CCR JEFERSON ADRIANO BRITO DOS SANTOS", pending: 60, delivered: 48 },
            { name: "TAC CARRO ADEJUNIO CAMARGO DOS SANTOS", pending: 14, delivered: 6 },
            { name: "TAC CARRO CCR JOSE MATHEUS GONÇALVES MIRANDA", pending: 74, delivered: 0 },
            { name: "TAC CARRO CCR HEITOR CARNEIRO ALVES", pending: 91, delivered: 0 },
            { name: "CEIN -DF", pending: 52, delivered: 193 },
            { name: "MEI CARRO - EMANOELA ARAUJO CAVALCANTE", pending: 13, delivered: 68 },
            { name: "TAC CARRO - EMANOEL RAPHAEL DE ARAUJO MAGALHAES", pending: 0, delivered: 51 },
            { name: "TAC CARRO - MANOEL COSTA CAVALCANTE NETO", pending: 39, delivered: 49 },
            { name: "MEI CARRO - ALLAN JACKSON CORREA DOS SANTOS", pending: 0, delivered: 25 },
            { name: "CEIS -DF", pending: 15, delivered: 163 },
            { name: "MEI CARRO - LUIZ ANTONIO RAMALHO DA CUNHA", pending: 11, delivered: 84 },
            { name: "MEI CARRO - KELLY LUANE PEREIRA SOARES", pending: 4, delivered: 79 },
            { name: "CGB 02-MT", pending: 175, delivered: 326 },
            { name: "TAC CARRO CGB LEO CRECIO DE FARIA", pending: 14, delivered: 89 },
            { name: "MEI CARRO CGB HIGOR MATHEUS AMARANTE THOME", pending: 58, delivered: 86 },
            { name: "TAC CARRO CGB VAGNER BATISTA CERQUEIRA", pending: 3, delivered: 64 },
            { name: "TAC CARRO JACSON DOUGLAS OLIVEIRA DE SOUZA", pending: 19, delivered: 34 },
            { name: "TAC CARRO CGB IOLANDA PARREIRA EREGIPE", pending: 38, delivered: 31 },
            { name: "TAC CARRO CGB ADEILTON DA SILVA MORAES", pending: 40, delivered: 22 },
            { name: "TAC CARRO CGB JESSIKA ALINE FERNANDES DIAS", pending: 3, delivered: 0 },
            { name: "CGB 03-MT", pending: 241, delivered: 533 },
            { name: "TAC CARRO CGB  MARCELO NEVES", pending: 38, delivered: 92 },
            { name: "TAC CARRO CGB LEONEL BENEDITO DE SOUZA ALMEIDA", pending: 2, delivered: 75 },
            { name: "TAC CARRO CGB  GRAZIANI BENEDITO DA SILVA", pending: 4, delivered: 75 },
            { name: "MEI CARRO CGB VILMAR MENDES DA SILVA", pending: 101, delivered: 63 },
            { name: "TAC CARRO CGB JAQUELINE REGINA PINHO DA COSTA", pending: 2, delivered: 51 },
            { name: "TAC CARRO - Thiago Moreira da Silva", pending: 30, delivered: 50 },
            { name: "TAC CARRO CGB DANIEL JONATHAN SANABRIA DA SILVA", pending: 62, delivered: 50 },
            { name: "TAC CARRO CGB DANILO RODRIGUES MARCELO", pending: 1, delivered: 49 },
            { name: "MEI CARRO CGB MICHELE ASSUNÇÃO PINHEIRO DE MOURA", pending: 0, delivered: 28 },
            { name: "TAC CARRO CGB003 DANIEL SIQUEIRA", pending: 1, delivered: 0 },
            { name: "CGB 04-MT", pending: 622, delivered: 187 },
            { name: "MEI CARRO CGB JOSE SOTERO DA COSTA JUNIOR", pending: 27, delivered: 50 },
            { name: "TAC CARRO CGB ROBERTO RIVELINO PIRES MODESTO", pending: 16, delivered: 39 },
            { name: "TAC CARRO CGB ALEXSANDRO CAMPOS DE MORAES", pending: 116, delivered: 33 },
            { name: "MEI CARRO CGB LEONY DA SILVA", pending: 61, delivered: 30 },
            { name: "TAC CARRO CGB WELYTON BATISTA CAMPOS", pending: 91, delivered: 22 },
            { name: "TAC CARRO CGB MARCIO JAIR DE MORAES", pending: 3, delivered: 13 },
            { name: "TAC CARRO CGB MARIO MARCIO MORAES DA SILVA", pending: 18, delivered: 0 },
            { name: "TAC MOTO CGB YESMER DE JESUS BRACA RUIZ", pending: 8, delivered: 0 },
            { name: "TAC CARRO CGB ELAINE ALENCAR SILVA CALISTO", pending: 65, delivered: 0 },
            { name: "TAC CARRO CGB VANYELLE DE AZEVEDO LEITE", pending: 24, delivered: 0 },
            { name: "TAC CARRO CGB MARIELLY NUNES SIQUEIRA", pending: 45, delivered: 0 },
            { name: "TAC CARRO CGB FLORISMAR ALVES DE AGUIAR JUNIOR", pending: 55, delivered: 0 },
            { name: "MEI CARRO CGB DASAYEVIS SEBASTIÃO MIRANDA DE LIMA", pending: 2, delivered: 0 },
            { name: "TAC CARRO CGB JESUS TONY DE ALENCAR CALISTO", pending: 91, delivered: 0 },
            { name: "CGB 05-MT", pending: 423, delivered: 201 },
            { name: "TAC CARRO CGB  JOSE CARLOS DA SILVA", pending: 49, delivered: 108 },
            { name: "TAC CARRO CGB LUCAS SANTOS SILVA", pending: 4, delivered: 64 },
            { name: "TAC CARRO CGB JOSE ROBERTO PINTO DA SILVA", pending: 56, delivered: 15 },
            { name: "TAC CARRO CGB DIELITTON WESLEN NASCIMENTO SPINELLI", pending: 22, delivered: 14 },
            { name: "MEI CARRO CGB FABIO SOUZA", pending: 141, delivered: 0 },
            { name: "TAC CARRO CGB EDISON DA GUIA MEIRA", pending: 50, delivered: 0 },
            { name: "TAC CARRO CGB EURICO CESAR SANTOS CARDOSO", pending: 39, delivered: 0 },
            { name: "MEI CARRO CGB FELIPE FAGNER SIQUEIRA COSTA", pending: 42, delivered: 0 },
            { name: "MEI CARRO CGB DANIEL FELICIANO DO NASCIMENTO FILHO", pending: 1, delivered: 0 },
            { name: "TAC CARRO CGB ALLYSON FIGUEIREDO MARIANO", pending: 12, delivered: 0 },
            { name: "TAC CARRO CGB ANDERSON BARONIO", pending: 7, delivered: 0 },
            { name: "CGR 02-MS", pending: 568, delivered: 368 },
            { name: "CARRO TAC ANDRESSA ALVES DE OLIVEIRA", pending: 5, delivered: 83 },
            { name: "MEI CARRO CGR 002 OVIDIO SALVADOR PASSARELI", pending: 34, delivered: 76 },
            { name: "TAC CARRO CD CGR ARQUILEY MARTINEZ DE OLIVEIRA", pending: 35, delivered: 67 },
            { name: "TAC CARRO CGR 002 HASER SANTOS QUIRINO", pending: 33, delivered: 52 },
            { name: "TAC CARRO CD CGR 002 SIDNEY ZANELLA CABRERA", pending: 38, delivered: 41 },
            { name: "TAC CARRO CGR 002 GEAN PEREIRA VIEIRA", pending: 86, delivered: 28 },
            { name: "TAC CARRO CGR 02 PRISCILLA DA SILVA JARA", pending: 55, delivered: 20 },
            { name: "TAC CARRO CGR 002 JEZREEL LESCANO OLIVEIRA", pending: 8, delivered: 1 },
            { name: "TAC CARRO CGR 002 VITOR BATISTA ROCHA", pending: 232, delivered: 0 },
            { name: "TAC CARRO CGR 002 NAHIN TEODORO DA COSTA ABDALLA", pending: 2, delivered: 0 },
            { name: "TAC CARRO CGR 002 LUCAS RODRIGUES DE MELO", pending: 40, delivered: 0 },
            { name: "CGR 03-MS", pending: 278, delivered: 313 },
            { name: "TAC CARRO CGR 003 VANDER COSTA PEREIRA", pending: 0, delivered: 84 },
            { name: "MEI CARRO CGR MESAQUE REIS DOS SANTOS", pending: 40, delivered: 61 },
            { name: "TAC CARRO CGR 003 CARLOS EDUARDO PAES", pending: 4, delivered: 47 },
            { name: "MEI CARRO CGR WILLIAM GONÇALVES PRECINATO", pending: 68, delivered: 46 },
            { name: "TAC CARRO CGR 003 ARTUR JORGE MAECAWA", pending: 29, delivered: 45 },
            { name: "TAC CARRO CGR 003 ADEMIRO FERREIRA LOPES", pending: 54, delivered: 30 },
            { name: "MEI CARRO CGR JOSELY IBANES VICENTE", pending: 81, delivered: 0 },
            { name: "TAC CARRO CGR 003 TIAGO DE OLIVEIRA GOMES", pending: 2, delivered: 0 },
            { name: "CGR 04-MS", pending: 227, delivered: 280 },
            { name: "TAC CARRO CGR 004 LEANDRO CAIQUE MENEZES DA SILVA", pending: 27, delivered: 63 },
            { name: "MEI CARRO CGR 004  JEFERSON DE ANDRADE", pending: 2, delivered: 53 },
            { name: "TAC CARRO CGR 04 ELI BORGES DE OLIVEIRA JUNIOR", pending: 6, delivered: 50 },
            { name: "TAC CARRO CGR 004 PAULO ROBERTO ESCOBAR DOS SANTOS", pending: 53, delivered: 45 },
            { name: "TAC CARRO CGR 04 ALEX ZANARIO DA SILVA DOS REIS", pending: 0, delivered: 42 },
            { name: "MEI CARRO CGR 004 MARCIANO LOPES RESQUIM JUNIOR", pending: 44, delivered: 24 },
            { name: "TAC MOTO CD CGR 004 ANDRE LUIS ROJAS GIMENES", pending: 92, delivered: 2 },
            { name: "TAC CARRO CGR 004 ANDRE LUIS PEREIRA DA SILVA", pending: 0, delivered: 1 },
            { name: "MEI CARRO CGR 04 EDENILSON ESPINDOLA DE CASTRO", pending: 2, delivered: 0 },
            { name: "CD CGR 004 LOGIN BAIXA", pending: 1, delivered: 0 },
            { name: "CGR 05-MS", pending: 280, delivered: 605 },
            { name: "TAC CARRO CGR VALDECIR ALVES DE CASTRO", pending: 36, delivered: 110 },
            { name: "TAC CARRO CGR 005 MARIA HELENA DA SILVA MATIAS", pending: 2, delivered: 107 },
            { name: "MEI CARRO CGR DIEGO CORREIA BARBOSA", pending: 10, delivered: 96 },
            { name: "MEI CGR 05 MS CARRO THIAGO OLIVEIRA DA VEIGA", pending: 0, delivered: 87 },
            { name: "TAC CARRO CGR 005 ALEXANDRE HOKAMA DUTRA", pending: 72, delivered: 84 },
            { name: "MEI CARRO CGR 005 MATHEUS CORDEIRO VILANOVA", pending: 43, delivered: 70 },
            { name: "MEI CARRO CGR 05 MS ANANIAS SOARES DE OLIVEIRA", pending: 46, delivered: 51 },
            { name: "MEI CARRO CGR 05 MS BRUNO DA SILVA DE ALMEIDA", pending: 68, delivered: 0 },
            { name: "LOGIN DE BAIXA CGR 005", pending: 3, delivered: 0 },
            { name: "CGR -MS", pending: 501, delivered: 327 },
            { name: "MEI CARRO CGR KEDSON FERREIRA DE AGUIAR", pending: 41, delivered: 84 },
            { name: "TAC CARRO CGR 001 KAUAN JUNIOR SILVA PAIVA", pending: 31, delivered: 83 },
            { name: "TAC CARRO CGR JENIFER CAROLINE DA SILVA CARISSIMO", pending: 22, delivered: 76 },
            { name: "TAC CARRO CGR 001 GEOVANA MARTINE ROCHA", pending: 77, delivered: 58 },
            { name: "TAC CARRO CGR THAINARA BOBADILHA DA MATA SOARES", pending: 34, delivered: 15 },
            { name: "TAC CARRO CGR ANDRE VENANCIO ORUE MEDINA", pending: 61, delivered: 10 },
            { name: "TAC MOTO CGR 001 VAGNER DOS SANTOS LIMA", pending: 186, delivered: 1 },
            { name: "TAC CARRO CD CGR RONNI PETERSON RAMIRES", pending: 9, delivered: 0 },
            { name: "TAC CARRO CGR 001 DEIVYD PAIVA MALAQUIAS", pending: 40, delivered: 0 },
            { name: "CHS -MS", pending: 17, delivered: 86 },
            { name: "TAC CARRO LUCIANA DE PAULA MENEZES", pending: 3, delivered: 51 },
            { name: "MEI CARRO CHS NEDIMAR DIAS B1", pending: 12, delivered: 32 },
            { name: "TAC CARRO CHS GLEICIANNE GOMES DOS SANTOS", pending: 2, delivered: 2 },
            { name: "TAC CARRO CHS GLAUCIELE DE SOUZA MACHADO", pending: 0, delivered: 1 },
            { name: "CMP-MT", pending: 337, delivered: 133 },
            { name: "AGR CARRO CMP PAULO FERNANDES DA CRUZ", pending: 40, delivered: 43 },
            { name: "MEI CARRO CMP EDUARDO LOPES DAMACENO", pending: 85, delivered: 34 },
            { name: "AGR CARRO CMP ENALIO BATISTA DAMASCENO", pending: 50, delivered: 21 },
            { name: "AGR CARRO CMP CLEIDI APARECIDA DE OLIVEIRA LOPES", pending: 17, delivered: 20 },
            { name: "TAC CARRO - ADILSON FERNANDES DE SOUSA MACHADO", pending: 6, delivered: 15 },
            { name: "TAC CARRO CMP DOUGLAS RENNER GONÇALVES DANTAS", pending: 12, delivered: 0 },
            { name: "MEI CARRO CMP ANADIR SANTANA DA SILVA E SILVA", pending: 127, delivered: 0 },
            { name: "CNF -MT", pending: 130, delivered: 117 },
            { name: "TAC MOTO CNF MIZAEL BORGES DA SILVA", pending: 54, delivered: 68 },
            { name: "TAC CARRO CNF JESSICA DALETEZZE DOS REIS", pending: 34, delivered: 31 },
            { name: "TAC CARRO CNF LUCIANO JUSTINO REIS", pending: 23, delivered: 16 },
            { name: "TAC CARRO CNF CARLOS MAGNO PINTO", pending: 9, delivered: 1 },
            { name: "TAC CARRO CNF PEDRO FERREIRA SILVA", pending: 7, delivered: 1 },
            { name: "TAC CARRO CNF THIAGO PEREIRA COSTA", pending: 2, delivered: 0 },
            { name: "TAC CARRO CNF VITHOR DA SILVA MACEDO", pending: 1, delivered: 0 },
            { name: "CRB -MS", pending: 670, delivered: 23 },
            { name: "TAC CARRO CRB Jeniffer Cori Aragon", pending: 15, delivered: 15 },
            { name: "TAC MOTO CRB SILVIA LUCIANA FORTES", pending: 222, delivered: 3 },
            { name: "TAC CARRO CRB Isabella Justiniano Marques", pending: 0, delivered: 3 },
            { name: "TAC CARRO CRB Adenilson felix", pending: 90, delivered: 2 },
            { name: "TAC CARRO CRB DAYANNE DE ARRUDA COELHO", pending: 96, delivered: 0 },
            { name: "TAC MOTO CRB Lethycia Mayara Almada Santana", pending: 27, delivered: 0 },
            { name: "MEI CARRO CGR PAULO MERCEDES ROCHA", pending: 171, delivered: 0 },
            { name: "TAC CARRO CRB Leufara de Araujo", pending: 49, delivered: 0 }
        ]
    },
    "CTL -GO": {
        totalPending: 698,
        totalDelivered: 8,
        totalOverall: 706,
        drivers: [
            { name: "TAC CARRO - CRISTIAN SILVEIRA CAMPOS", pending: 95, delivered: 7 },
            { name: "TAC CARRO - WANDERLEY JACOB RODRIGUES", pending: 154, delivered: 1 },
            { name: "TAC CARRO - ELENILTON JOSE ALVES", pending: 131, delivered: 0 },
            { name: "MEI CARRO - JESSICA MENDES ARAUJO", pending: 2, delivered: 0 },
            { name: "MEI CARRO - DAILON MORAIS ALVES", pending: 313, delivered: 0 },
            { name: "MEI CARRO - JOAO SOARES DE MELO NETO", pending: 1, delivered: 0 },
            { name: "MEI CARRO - WARLEY SOARES CAMPOS", pending: 2, delivered: 0 }
        ]
    },
    "CTN -GO": {
        totalPending: 148,
        totalDelivered: 47,
        totalOverall: 195,
        drivers: [
            { name: "TAC CARRO - DIRCEU ALVES DE SANTANA JUNIOR", pending: 103, delivered: 46 },
            { name: "MEI CARRO - JANAINA DOS SANTOS DE MORAIS PEREIRA", pending: 43, delivered: 1 },
            { name: "TAC CARRO - PAULO HENRIQUE BARBOSA SOARES", pending: 2, delivered: 0 },
            { name: "CXM -MS", pending: 123, delivered: 1 },
            { name: "MEI MOTO CXM - GIULIANO FREITAS PEREIRA", pending: 0, delivered: 1 },
            { name: "TAC CARRO JESSICA SILVA DE CARVALHO", pending: 1, delivered: 0 },
            { name: "TAC MOTO ANTONIO MARTINS CUSTODIO", pending: 79, delivered: 0 },
            { name: "MEI MOTO CXM SIRLEIA APARECIDA RODRIGUES AMORIM", pending: 43, delivered: 0 },
            { name: "CZS -AC", pending: 7, delivered: 1 },
            { name: "TAC MOTO - EMANUEL DA SILVA SANTOS", pending: 2, delivered: 1 },
            { name: "TAC MOTO RAELITON  DE SOUZA SILVA", pending: 1, delivered: 0 },
            { name: "TAC MOTO - MATEUS MIRANDA SILVA", pending: 4, delivered: 0 },
            { name: "DOU 02-MS", pending: 290, delivered: 1 },
            { name: "TAC CARRO DUILIO EDUARDO TORRACA", pending: 97, delivered: 1 },
            { name: "TAC CARRO DOU JORGE DIAS DO AMARAL", pending: 76, delivered: 0 },
            { name: "MEI CARRO DOU 02 MAYKON JAIR FERREIRA", pending: 36, delivered: 0 },
            { name: "MEI CARRO DOU NEVERTON NEEMIAS DA SILVA BARBOSA", pending: 1, delivered: 0 },
            { name: "TAC CARRO DOU02 ANIELY YASMINI MACEDO MEIRELES", pending: 60, delivered: 0 },
            { name: "MEI CARRO DOU OSVALDO RIBEIRO JUNIOR", pending: 1, delivered: 0 },
            { name: "MEI CARRO DOU02 OZEIAS DOS PASSOS ROMERO", pending: 19, delivered: 0 },
            { name: "DOU -MS", pending: 860, delivered: 4 },
            { name: "TAC MOTO DOU LEILA VIEIRA DA SILVA", pending: 166, delivered: 3 },
            { name: "TAC CARRO DOU FERNANDA LOBO VIEIRADA SILVA", pending: 7, delivered: 1 },
            { name: "TAC MOTO DOU ANDREIA BARBOSA MACEDO MEIRELES", pending: 33, delivered: 0 },
            { name: "MEI MOTO DOU PATRICK HERNANY ALVES DA SILVA", pending: 127, delivered: 0 },
            { name: "TAC MOTO DOU LUCAS DE ARAUJO PAES DIAS", pending: 74, delivered: 0 },
            { name: "TAC CARRO DOU 001 ROSANA BORGES VILHALVA", pending: 6, delivered: 0 },
            { name: "TAC CARRO DOU SUELLEN DA SILVA RAMOS", pending: 94, delivered: 0 },
            { name: "TAC CARRO DOU ANDRESA CHAVES DUTRA", pending: 20, delivered: 0 },
            { name: "MEI CARRO DOU RODRIGO SOARES", pending: 54, delivered: 0 },
            { name: "TAC CARRO DOU BRUNO LEONARDO FRANTZ", pending: 121, delivered: 0 },
            { name: "TAC MOTO DOU SANDERSON ANTUNES", pending: 109, delivered: 0 },
            { name: "LOGIN BAIXAS - LEBRON JAMES", pending: 13, delivered: 0 },
            { name: "TAC CARRO DOU NAARIEL WILLIAN DA SILVA", pending: 36, delivered: 0 },
            { name: "EMA -DF", pending: 95, delivered: 169 },
            { name: "MEI CARRO - JONATA SILVA CUTRIM", pending: 13, delivered: 63 },
            { name: "MEI CARRO - MAXWELL GOMES DE JESUS", pending: 37, delivered: 46 },
            { name: "MEI CARRO - MARIA JOSE DA ROCHA", pending: 5, delivered: 45 },
            { name: "MEI CARRO - ANA CLAUDIA DE SA GUIMARAES", pending: 20, delivered: 9 },
            { name: "TAC CARRO - INALDO SOARES SILVA FILHO", pending: 20, delivered: 6 },
            { name: "F AGL-GO", pending: 353, delivered: 272 },
            { name: "TAC CARRO - ANDERSON DE JESUS", pending: 3, delivered: 65 },
            { name: "MEI CARRO - WALLACE ARAUJO TEODORO", pending: 5, delivered: 63 },
            { name: "TAC CARRO - JHONATA NOBREGA DINIZ", pending: 13, delivered: 53 },
            { name: "TAC MOTO - RODRIGO ALVES LEITE", pending: 3, delivered: 33 },
            { name: "MEI CARRO - DANILO SOUSA DA SILVA", pending: 19, delivered: 33 },
            { name: "ETC CARRO F AGL - MATEUS WILLIAM DE SOUSA SALES", pending: 35, delivered: 22 },
            { name: "TAC CARRO - JORGE NASCIMENTO PEREIRA JUNIOR", pending: 25, delivered: 3 },
            { name: "MEI CARRO - FERNANDA SOUZA BARROS", pending: 90, delivered: 0 },
            { name: "F AGL - RONIEL DE PAULA MARES", pending: 43, delivered: 0 },
            { name: "TAC CARRO - GABRIELE FERREIRA XAVIER", pending: 1, delivered: 0 },
            { name: "ETC CARRO F AGL - VALERIANO DO REIS SOARES", pending: 116, delivered: 0 },
            { name: "F FMA-GO", pending: 197, delivered: 216 },
            { name: "MEI CARRO - ZELI RIBEIRO GUIMARAES", pending: 0, delivered: 72 },
            { name: "ETC CARRO F FMA - DAIANNE FERNANDES DA SILVA", pending: 133, delivered: 46 },
            { name: "ETC MOTO FMA - JOAO VICTOR RODRIGUES DOS SANTOS", pending: 2, delivered: 46 },
            { name: "MEI CARRO - GENIR TEIXEIRA BARBOSA", pending: 0, delivered: 23 },
            { name: "TAC CARRO - JOILSON PEREIRA DOS SANTOS", pending: 42, delivered: 20 },
            { name: "ETC MOTO F FMA - ELIELTON ALVARES DE SOUSA", pending: 6, delivered: 4 },
            { name: "ETC MOTO FMA - EDGAR VANDERELEY DE SOUSA", pending: 14, delivered: 4 },
            { name: "TAC CARRO - FLAVIO VIEIRA RODRIGUES", pending: 0, delivered: 1 },
            { name: "FMA -GO", pending: 1, delivered: 0 },
            { name: "TAC CARRO - LUIS DANILO SANTOS CARVALHO", pending: 1, delivered: 0 },
            { name: "GAM -DF", pending: 62, delivered: 180 },
            { name: "TAC CARRO - KLEBER SILVA DE ALMEIDA", pending: 27, delivered: 100 },
            { name: "TAC CARRO - JORGE HENRIQUE NAZARIO C DE FREITAS", pending: 0, delivered: 42 },
            { name: "TAC CARRO - LEONARDO DA CUNHA SILVA", pending: 35, delivered: 38 }
        ]
    },
    "PON -GO": {
        totalPending: 143,
        totalDelivered: 0,
        totalOverall: 143,
        drivers: [
            { name: "MEI CARRO - GUILHERME MORAIS COSTA", pending: 95, delivered: 0 },
            { name: "MEI CARRO - ALEKSANDER KAMENAK DIAS DE MELO", pending: 48, delivered: 0 },
            { name: "POS -GO", pending: 3, delivered: 0 },
            { name: "TAC CARRO - SIRLEI ALVES DOS SANTOS", pending: 2, delivered: 0 },
            { name: "TAC CARRO - GABRIEL GUIMARAES LUCENA", pending: 1, delivered: 0 }
        ]
    },
    "TRD -GO": {
        totalPending: 273,
        totalDelivered: 158,
        totalOverall: 431,
        drivers: [
            { name: "TAC CARRO - RENATO GONCALVES BUENO", pending: 17, delivered: 67 },
            { name: "MEI CARRO - DAVI BARBOSA NOBRE", pending: 10, delivered: 33 },
            { name: "MEI CARRO - SIMONE ALVES DE SOUZA", pending: 26, delivered: 29 },
            { name: "MEI CARRO - SAMUEL NEVES DE MELO SILVA", pending: 11, delivered: 28 },
            { name: "TAC CARRO - JEAN JEFERSON SOARES FERREIRA", pending: 0, delivered: 1 },
            { name: "MEI CARRO - ANDREIA RODRIGUES DE OLIVEIRA", pending: 115, delivered: 0 },
            { name: "TAC CARRO - CLEOMAR NONATO DA LUZ", pending: 3, delivered: 0 },
            { name: "TAC CARRO - JULIANO FERREIRA PIRES", pending: 91, delivered: 0 }
        ]
    },
    "GYN 02-GO": {
        totalPending: 385,
        totalDelivered: 249,
        totalOverall: 634,
        drivers: [
            { name: "TAC CARRO - AURELIANO EURIPEDES DE PAULA TRINDADE", pending: 65, delivered: 100 },
            { name: "TAC CARRO - VINICIUS VIGNER DE ALMEIDA", pending: 40, delivered: 75 },
            { name: "TAC CARRO - LUCAS MATOS DA SILVA", pending: 64, delivered: 74 },
            { name: "MEI CARRO - WISLEY ALVES DA SILVA", pending: 123, delivered: 0 },
            { name: "MEI CARRO - CLAUDIO MOREIRA CARVALHO", pending: 2, delivered: 0 },
            { name: "TAC CARRO - SARA CRISTINE RIBEIRO DOS SANTOS", pending: 91, delivered: 0 }
        ]
    },
    "GYN 03-GO": {
        totalPending: 633,
        totalDelivered: 1023,
        totalOverall: 1656,
        drivers: [
            { name: "MEI CARRO - RENATO REZENDE DE BARROS", pending: 29, delivered: 118 },
            { name: "TAC CARRO - VINICIUS MAIONE SILVA CRUZ", pending: 2, delivered: 117 },
            { name: "TAC CARRO - JEZIEL FIGUEIRA GOMES", pending: 7, delivered: 93 },
            { name: "MEI CARRO - FABRICIO ALVES PACHECO", pending: 5, delivered: 92 },
            { name: "TAC CARRO - EDSON LUIS DE OLIVEIRA", pending: 16, delivered: 83 },
            { name: "MEI CARRO - WESLEY DIVINO FRANCO", pending: 100, delivered: 80 },
            { name: "MEI CARRO - LEANDRO MANOEL DA SILVA", pending: 64, delivered: 69 },
            { name: "TAC CARRO -  WYVES RIOS MORAES", pending: 1, delivered: 63 },
            { name: "TAC CARRO - STEFANNY BORGES DOS SANTOS", pending: 48, delivered: 59 },
            { name: "TAC CARRO - UEDSON MARQUES MOITINHO", pending: 49, delivered: 54 },
            { name: "TAC CARRO - LUCAS FERREIRA ALVES MENDONCA", pending: 0, delivered: 53 },
            { name: "TAC CARRO - WALDEMIR SANTANA DA COSTA", pending: 5, delivered: 35 },
            { name: "MEI CARRO - DIEGO LIMA REGO", pending: 32, delivered: 34 },
            { name: "MEI CARRO - THIAGO ROSA VITURINO", pending: 130, delivered: 32 },
            { name: "TAC CARRO - LAIS MACHADO DOS SANTOS SOUZA", pending: 0, delivered: 16 },
            { name: "MEI CARRO - MATEUS PEREIRA CAETANO", pending: 25, delivered: 15 },
            { name: "TAC CARRO - GIOVANNI HENRIQUE ALVES ALVIM", pending: 32, delivered: 10 },
            { name: "TAC CARRO - WEMERSON PEREIRA MENDES", pending: 57, delivered: 0 },
            { name: "TAC CARRO - HUGO FERREIRA FARIA", pending: 31, delivered: 0 }
        ]
    },
    "GYN 04-GO": {
        totalPending: 383,
        totalDelivered: 193,
        totalOverall: 576,
        drivers: [
            { name: "TAC CARRO - GLEYBE RENATO ANDRADE", pending: 105, delivered: 106 },
            { name: "TAC CARRO - CARLOS HELIABY NEVES VIEIRA", pending: 77, delivered: 87 },
            { name: "TAC CARRO - SEGINALDO ANTONIO DA SILVA", pending: 16, delivered: 0 },
            { name: "TAC CARRO - JORDANA MENDES DE SOUSA", pending: 19, delivered: 0 },
            { name: "MEI CARRO - PEDRO HENRIQUE PORFIRIO DE OLIVEIRA", pending: 165, delivered: 0 },
            { name: "TAC CARRO - ANNA KARENINA", pending: 1, delivered: 0 }
        ]
    },
    "GYN 05-GO": {
        totalPending: 263,
        totalDelivered: 229,
        totalOverall: 492,
        drivers: [
            { name: "TAC CARRO - DEUSDETE FERREIRA DA ROCHA", pending: 130, delivered: 126 },
            { name: "TAC CARRO - MARCIONILIO MOREIRA BARBOSA", pending: 114, delivered: 92 },
            { name: "TAC CARRO - LEORGINA MARIA DUTRA SILVA JACINTO", pending: 19, delivered: 11 }
        ]
    },
    "GYN 06-GO": {
        totalPending: 546,
        totalDelivered: 425,
        totalOverall: 971,
        drivers: [
            { name: "TAC CARRO - WAGNER DIAS JUNIOR", pending: 77, delivered: 128 },
            { name: "TAC CARRO - AMANCIO MARIANO FIRMINO FILHO", pending: 17, delivered: 84 },
            { name: "MEI CARRO - LUIZ FELIPE DE ABREU ROCHA", pending: 107, delivered: 55 },
            { name: "MEI CARRO - JULIENE DAYSE VASCONCELOS DA COSTA", pending: 77, delivered: 52 },
            { name: "TAC CARRO - PRISCILA GENOVESI BOCCHI", pending: 85, delivered: 47 },
            { name: "MEI CARRO - WANDERSON BARROS DA SILVA", pending: 105, delivered: 36 },
            { name: "MEI CARRO - LEONILDA DA SILVA BRAGA CORDOVIL", pending: 77, delivered: 23 },
            { name: "TAC CARRO - RAFAELA DOSTOIEVSKI", pending: 1, delivered: 0 }
        ]
    },
    "GYN 07-GO": {
        totalPending: 377,
        totalDelivered: 288,
        totalOverall: 665,
        drivers: [
            { name: "TAC CARRO - WASHINGTON FERREIRA", pending: 33, delivered: 85 },
            { name: "MEI CARRO - GEOVANE DOS SANTOS OLIVEIRA", pending: 5, delivered: 47 },
            { name: "TAC CARRO - PAULO HENRIQUE FERNANDES DA SILVA", pending: 1, delivered: 46 },
            { name: "TAC CARRO - SIRLEY CASTILHO CABRAL DA CRUZ", pending: 0, delivered: 40 },
            { name: "TAC CARRO - WELLINGTON RIBEIRO DE LIMA", pending: 65, delivered: 24 },
            { name: "MEI CARRO - MARCOS JUNIO BUENO DE OLIVEIRA", pending: 89, delivered: 18 },
            { name: "TAC CARRO - SILOMI MATIAS PEREIRA", pending: 5, delivered: 17 },
            { name: "MEI CARRO - WELLIKY MOREIRA DE CARVALHO", pending: 67, delivered: 10 },
            { name: "TAC CARRO - ANNE CAROLINY ALVES DOS REIS", pending: 73, delivered: 1 },
            { name: "TAC CARRO - JOSUE PEDRO ALVES GOMES", pending: 39, delivered: 0 }
        ]
    },
    "ITR -GO": {
        totalPending: 433,
        totalDelivered: 11,
        totalOverall: 444,
        drivers: [
            { name: "MEI CARRO - TAUANE SANTOS OLIVEIRA", pending: 143, delivered: 10 },
            { name: "MEI CARRO - ALLYSSON BELCKYOR GOMES E SILVA", pending: 90, delivered: 1 },
            { name: "MEI MOTO - PEDRO HENRIQUE SILVA OLIMPIO DOS SANTOS", pending: 41, delivered: 0 },
            { name: "MEI CARRO - LENE ROSILDA DE JESUS SANTOS", pending: 159, delivered: 0 },
            { name: "JPN -RO", pending: 21, delivered: 1 },
            { name: "TAC CARRO SANDOVALDO DOS SANTOS FILHO", pending: 0, delivered: 1 },
            { name: "TAC MOTO CLAUDIO OLIVEIRA PACATONI", pending: 16, delivered: 0 },
            { name: "TAC CARRO STANLEY EDUARDO REGO SILVA MAIO", pending: 1, delivered: 0 },
            { name: "TAC CARRO SABLINE FREITAS MARCOLINO", pending: 3, delivered: 0 },
            { name: "TAC CARRO LUCIVANE MARIA DE SOUZA", pending: 1, delivered: 0 },
            { name: "JRD -MS", pending: 727, delivered: 24 },
            { name: "TAC-CARRO - EDGAR DUTRA DA LUZ", pending: 58, delivered: 15 },
            { name: "MEI - CARRO VINICIUS GAVILAN LEDESMA CHAVES", pending: 85, delivered: 9 },
            { name: "TAC - CARRO DIJANIR HORTÊNCIO", pending: 176, delivered: 0 },
            { name: "TAC CARRO - DOUGLAS LUIS DOS SANTOS LARREIA", pending: 21, delivered: 0 },
            { name: "TAC CARRO JRD JAMIL PEDRO FILHO", pending: 5, delivered: 0 },
            { name: "MEI CARRO - MISELY VICENTE SOARES", pending: 1, delivered: 0 },
            { name: "ETC CARRO - RONALDO MENDONCA DOS SANTOS", pending: 280, delivered: 0 },
            { name: "TAC - CARRO - FILIPE SILVA BENNETT", pending: 101, delivered: 0 }
        ]
    },
    "JTI -GO": {
        totalPending: 66,
        totalDelivered: 1,
        totalOverall: 67,
        drivers: [
            { name: "TAC CARRO - VALDIVINO CARLOS DE MORAIS", pending: 0, delivered: 1 },
            { name: "TAC CARRO - MARCELO FERNANDO NOGUEIRA", pending: 47, delivered: 0 },
            { name: "MEI CARRO - GUILHERME RODRIGUES ROCHA FARIAS", pending: 2, delivered: 0 },
            { name: "TAC CARRO - HELLEN OLIVEIRA DE AZARIAS", pending: 17, delivered: 0 },
            { name: "JUI -MT", pending: 99, delivered: 202 },
            { name: "MEI CARRO JUI KELLY DA NOBREGA GOMES", pending: 4, delivered: 151 },
            { name: "MEI CARRO JUI ELIO LOURENCO DE OLIVEIRA", pending: 38, delivered: 41 },
            { name: "TAC CARRO JUI RAILANDE RODRIGUES SENA", pending: 50, delivered: 6 },
            { name: "TAC CARRO JUI ELIANE MARTINS", pending: 0, delivered: 2 },
            { name: "TAC MOTO JUI EDER MATHEUS RODRIGUES DOS SANTOS", pending: 0, delivered: 1 },
            { name: "MEI CARRO JUI LAUDICEIA DOS SANTOS DE SA IGNACIO", pending: 7, delivered: 1 },
            { name: "LRV -MT", pending: 778, delivered: 15 },
            { name: "TAC CARRO -  VICTOR SILVA DOS SANTOS", pending: 84, delivered: 9 },
            { name: "TAC CARRO LRV KEYSTON RODRIGUES PEREIRA", pending: 104, delivered: 2 },
            { name: "TAC CARRO LRV MATHEUS BEZERRA DA SILVA CASOLL", pending: 161, delivered: 1 },
            { name: "TAC CARRO LRV LUCIENE MIRANDA DA SILVA", pending: 46, delivered: 1 },
            { name: "TAC CARRO LRV ALESSON CESAR DOS SANTOS", pending: 35, delivered: 1 },
            { name: "TAC CARRO LRV LEONARDO MONTEIRO DO NASCIMENTO", pending: 74, delivered: 1 },
            { name: "TAC CARRO LRV SIMONE NAUMANN", pending: 54, delivered: 0 },
            { name: "TAC CARRO LRV MAYCON CLAYTON SILVA SOARES", pending: 77, delivered: 0 },
            { name: "TAC CARRO LRV GABRIEL DA SILVA CARVALHO", pending: 7, delivered: 0 },
            { name: "TAC CARRO LRV EVERTON SILVA SOARES", pending: 136, delivered: 0 },
            { name: "LUZ -GO", pending: 41, delivered: 212 },
            { name: "TAC CARRO - MATEUS SANTOS GOMES", pending: 5, delivered: 62 },
            { name: "TAC CARRO - LEILA JULLIANA AFONSO DE ABREU", pending: 3, delivered: 60 },
            { name: "TAC CARRO - DAIANA LEMOS DOS SANTOS", pending: 30, delivered: 53 },
            { name: "TAC CARRO - ERICK ALYSSON RABELO", pending: 3, delivered: 37 },
            { name: "MDT -MT", pending: 65, delivered: 35 },
            { name: "TAC CARRO - RONIVON RAMOS DA SILVA FEITOSA", pending: 19, delivered: 35 },
            { name: "TAC CARRO MDT LUANA ALVES NASCIMENTO", pending: 6, delivered: 0 },
            { name: "MEI CARRO MDT IAGO CONSTANTINO DE OLIVEIRA", pending: 40, delivered: 0 },
            { name: "NDI -MS", pending: 165, delivered: 33 },
            { name: "TAC CARRO NDI VALDECIR MARTINS VAIS", pending: 1, delivered: 27 },
            { name: "TAC CARRO NDI HELIENE MAGALHOES DE MIRANDA SANTOS", pending: 85, delivered: 6 },
            { name: "MEI CARRO DOU EVANDRO JOSE SIQUEIRA", pending: 1, delivered: 0 },
            { name: "MEI CARRO NDI DANILO JOSE MORAES", pending: 42, delivered: 0 },
            { name: "TAC CARRO NDI NAYARA BARRETO SANTOS RAYMUNDO", pending: 36, delivered: 0 },
            { name: "NVR -MS", pending: 269, delivered: 0 },
            { name: "TAC MOTO ADEMIR APARECIDO GOSLISKI", pending: 118, delivered: 0 },
            { name: "TAC MOTO TANI CRISTINA PAVEZI", pending: 66, delivered: 0 },
            { name: "TAC MOTO EMILY LUISA DA SILVA FERREIRA", pending: 85, delivered: 0 },
            { name: "NVT -MT", pending: 814, delivered: 78 },
            { name: "TAC CARRO NVT EBER DA COSTA AMARAL", pending: 74, delivered: 27 },
            { name: "TAC CARRO NVT MICHELE GONÇALVES DE SANTANA", pending: 63, delivered: 17 },
            { name: "TAC CARRO NVT GEAZI HENRIQUE MOREIRA PEREIRA", pending: 66, delivered: 14 },
            { name: "TAC CARRO NVT DIONATA DA COSTA VINHOTE", pending: 59, delivered: 8 },
            { name: "TAC MOTO NVT ANGELICA CRISTINA DO NASCIMENTO", pending: 53, delivered: 7 },
            { name: "TAC CARRO NVT DIOGNES DA SILVA TASSOTTI", pending: 79, delivered: 5 },
            { name: "MEI CARRO NVT SAMUEL RIBEIRO JUNIOR", pending: 77, delivered: 0 },
            { name: "TAC CARRO NVT LETICIA LAMPERT", pending: 104, delivered: 0 },
            { name: "TAC CARRO NVT ODINEI SANTANA", pending: 3, delivered: 0 },
            { name: "TAC CARRO  NVT ALVINO PEREIRA", pending: 65, delivered: 0 },
            { name: "TAC CARRO NVT JACKELINE NASCIMENTO LEAL ROSA", pending: 27, delivered: 0 },
            { name: "TAC CARRO NVT JOAO PAULO MENDONÇA AZEVEDO", pending: 144, delivered: 0 },
            { name: "OCD-GO", pending: 137, delivered: 199 },
            { name: "MEI CARRO - MARCIA MARIA LINDOMAR", pending: 4, delivered: 56 },
            { name: "MEI CARRO - WASHINGTON FIRMINO DA COSTA", pending: 1, delivered: 47 },
            { name: "TAC CARRO - ISAQUE SOARES VITORIO", pending: 2, delivered: 43 },
            { name: "TAC CARRO - DANILO ROMULO GOMES GONCALVES", pending: 36, delivered: 30 },
            { name: "MEI CARRO - JOSE WILLIAN DE JESUS SILVA", pending: 1, delivered: 23 },
            { name: "MEI CARRO - KATIANA MESSIAS LOPES CAMELO", pending: 93, delivered: 0 },
            { name: "PLDF -DF", pending: 92, delivered: 158 },
            { name: "TAC CARRO - ANDRE DOS SANTOS COSTA", pending: 3, delivered: 67 },
            { name: "MEI CARRO - RAFAEL ALVES DA SILVA", pending: 14, delivered: 47 },
            { name: "MEI CARRO - NEURIANE MENDES COSTA", pending: 23, delivered: 27 },
            { name: "TAC CARRO - GLEYCI FERREIRA COELHO", pending: 48, delivered: 17 },
            { name: "TAC CARRO - AMANDA BEZERRA DOS OLIVEIRA", pending: 4, delivered: 0 },
            { name: "PLN -GO", pending: 3, delivered: 0 },
            { name: "MEI CARRO - ESTENIO GOMES AFFONSO", pending: 3, delivered: 0 },
            { name: "PNT-MS", pending: 351, delivered: 3 },
            { name: "TAC CARRO PNT PAULO ROBERTO CARVALHO", pending: 72, delivered: 1 },
            { name: "TAC MOTO PNT JEAN CARLOS JACQUES", pending: 1, delivered: 1 },
            { name: "TAC CARRO PNT JONATAN PAIM RIVAS", pending: 138, delivered: 1 },
            { name: "TAC PNT CARRO ROZELEI LIMA MOURA", pending: 51, delivered: 0 },
            { name: "TAC CARRO PNT THIAGO HENRIQUE VERÃO JARA", pending: 13, delivered: 0 },
            { name: "TAC CARRO PNT SUZANA BEATRIZ RODRIGUES GOMES", pending: 76, delivered: 0 }
        ]
    },
    "QUI -GO": {
        totalPending: 1,
        totalDelivered: 0,
        totalOverall: 1,
        drivers: [
            { name: "TAC CARRO - WESLEY LIMA REZENDE", pending: 1, delivered: 0 },
            { name: "RBR 02-AC", pending: 186, delivered: 6 },
            { name: "TAC CARRO MARIANA MARCELE DOS REIS FRANCA", pending: 0, delivered: 6 },
            { name: "TAC MOTO - CARLOS WEIGLAS MARTINS DE CASTRO", pending: 132, delivered: 0 },
            { name: "TAC CARRO - Luís Felipe Soares Onofre", pending: 54, delivered: 0 },
            { name: "RBR -AC", pending: 365, delivered: 4 },
            { name: "TAC CARRO SEBASTIANA QUEIROZ DA SILVA", pending: 1, delivered: 2 },
            { name: "TAC CARRO LEONARDO DA SILVA NASCIMENTO", pending: 0, delivered: 1 },
            { name: "TAC CARRO REINALDO FERREIRA LIMA", pending: 0, delivered: 1 },
            { name: "TAC CARRO - KELVYS ARCANJO MACIEL", pending: 121, delivered: 0 },
            { name: "TAC MOTO JHONY SILVA CARVALHO", pending: 1, delivered: 0 },
            { name: "TAC CARRO - RITHARLYS FERREIRA DE ALENCAR FREIRE", pending: 122, delivered: 0 },
            { name: "TAC CARRO - Jefferson Alves Brito", pending: 77, delivered: 0 },
            { name: "TAC CARRO ANDERSON DE SOUZA BARBOSA", pending: 43, delivered: 0 },
            { name: "RDM -RO", pending: 1394, delivered: 139 },
            { name: "TAC CARRO RAFAEL GOMES DE ARAUJO", pending: 160, delivered: 59 },
            { name: "TAC CARRO SANDRA LUCIMAR RODRIGUES", pending: 6, delivered: 31 },
            { name: "MEI CARRO EDER ANTONIO ELLY", pending: 175, delivered: 16 },
            { name: "TAC CARRO SAMARA CRISTINA PAULI", pending: 18, delivered: 15 },
            { name: "TAC CARRO MATEUS SOARES PROCHNOW", pending: 269, delivered: 15 },
            { name: "TAC CARRO PAULO HENRIQUE BOONE DA SILVA", pending: 123, delivered: 2 },
            { name: "TAC CARRO DOUGLAS SIQUEIRA FIRMINO", pending: 189, delivered: 1 },
            { name: "TAC CARRO DAIANE GHILARDI", pending: 135, delivered: 0 },
            { name: "TAC CARRO RENATA KATHIELI GRACIOLLI", pending: 33, delivered: 0 },
            { name: "TAC CARRO GILMAR RODRIGUES DA SILVA", pending: 91, delivered: 0 },
            { name: "TAC CARRO JOSE REGINALDO XAVIER", pending: 52, delivered: 0 },
            { name: "TAC CARRO KELLY DE JESUS GONCALVES", pending: 87, delivered: 0 },
            { name: "TAC CARRO QUEMHUEL ALVES DA SILVA", pending: 56, delivered: 0 },
            { name: "RFI -DF", pending: 313, delivered: 99 },
            { name: "TAC CARRO - DANIEL ROBERTO DOS SANTOS NEVES", pending: 31, delivered: 54 },
            { name: "TAC CARRO - RAFAELA SILVA BRITO DAS CHAGAS", pending: 20, delivered: 40 },
            { name: "TAC CARRO - FRANCISCO ANTONIO PEREIRA DA SILVA", pending: 85, delivered: 3 },
            { name: "TAC CARRO - MARTA HELENA CASTRO DE SOUZA", pending: 91, delivered: 2 },
            { name: "TAC CARRO - HEULER BEZERRA DE OLIVEIRA", pending: 86, delivered: 0 },
            { name: "ROO -MT", pending: 1917, delivered: 544 },
            { name: "TAC CARRO ROO ISCK ENIO DOS SANTOS", pending: 24, delivered: 135 },
            { name: "MEI CARRO ROO TIAGO GILSON ALVES DA SILVA", pending: 57, delivered: 102 },
            { name: "MEI CARRO ROO ADMILSON PEREIRA BARBOSA", pending: 109, delivered: 98 },
            { name: "MEI CARRO ROO WAGNER FERNANDO DA SILVA MAGALHAES", pending: 77, delivered: 71 },
            { name: "MEI CARRO ROO DANIEL DE JESUS SOUZA", pending: 44, delivered: 49 },
            { name: "AGR CARRO ROO AILSON PEREIRA BARBOSA", pending: 101, delivered: 42 },
            { name: "AGR CARRO ROO JEFTE CHARLLES PAES", pending: 17, delivered: 24 },
            { name: "MEI CARRO ROO CLAUDEIR RODRIGUES", pending: 184, delivered: 19 },
            { name: "MEI CARRO ROO RODRIGO MARCEL BARBOSA DOS SANTOS", pending: 28, delivered: 2 },
            { name: "AGR CARRO ROO THEYDH AYNNE DORNE", pending: 0, delivered: 2 },
            { name: "MEI CARRO ROO - DAMASCENO DOS SANTOS", pending: 225, delivered: 0 },
            { name: "MEI CARRO ROO FERNANDO DE ALMEIDA DOURADO", pending: 10, delivered: 0 },
            { name: "TAC CARRO ROO KLAISTON", pending: 61, delivered: 0 },
            { name: "MEI CARRO ROO ATILA OLIVEIRA COELHO", pending: 126, delivered: 0 },
            { name: "MEI CARRO ROO LUCAS RODRIGUES LOPES", pending: 170, delivered: 0 },
            { name: "AGR CARRO ROO ARA  ERNANE SANTOS", pending: 35, delivered: 0 },
            { name: "AGR CARRO ROO MARK OURO BRANCO", pending: 42, delivered: 0 },
            { name: "MEI CARRO FLAVIA PEDRA PRETA", pending: 219, delivered: 0 },
            { name: "AGR CARRO ROO GUSTAVO SALVIAN", pending: 117, delivered: 0 },
            { name: "AGR CARRO ROO WATILLA HENRIQUE GONÇALVES", pending: 156, delivered: 0 },
            { name: "MEI CARRO GGA LAISON BRUNO", pending: 1, delivered: 0 },
            { name: "MEI CARRO ROO FERNANDO AUGUSTO DA SILVA MAGALHAES", pending: 114, delivered: 0 }
        ]
    },
    "RVD -GO": {
        totalPending: 146,
        totalDelivered: 19,
        totalOverall: 165,
        drivers: [
            { name: "TAC CARRO - FLAUBER STEFANIO MORENO", pending: 4, delivered: 14 },
            { name: "MEI CARRO - VIVIANA DIAS DA COSTA", pending: 59, delivered: 4 },
            { name: "TAC CARRO - SAMARA KELLIS PEREIRA DOS SANTOS", pending: 2, delivered: 1 },
            { name: "MEI CARRO - EULLER SOARES VIEIRA", pending: 81, delivered: 0 },
            { name: "SAMS -DF", pending: 77, delivered: 211 },
            { name: "TAC CARRO - LUIZA SOARES DE OLIVEIRA", pending: 22, delivered: 54 },
            { name: "TAC CARRO - PABLO VIEIRA MOREIRA", pending: 1, delivered: 49 },
            { name: "TAC CARRO - EDMILSON DIAS DE OLIVEIRA", pending: 34, delivered: 44 },
            { name: "TAC CARRO - MARYNEIDE DE ALBUQUERQUE FERNANDES", pending: 10, delivered: 41 },
            { name: "TAC MOTO - ROGERIO FERNANDES DOS ANJOS", pending: 0, delivered: 9 },
            { name: "TAC MOTO - VINICIUS LISBOA NUNES", pending: 0, delivered: 8 },
            { name: "TAC MOTO - AGNES CARDOSO CIRQUEIRA", pending: 0, delivered: 6 },
            { name: "TAC MOTO - DJAKES LIMA DE OLIVEIRA", pending: 10, delivered: 0 },
            { name: "SBN -DF", pending: 274, delivered: 305 },
            { name: "TAC CARRO - DANIELE SILVA COSTA", pending: 3, delivered: 86 },
            { name: "TAC CARRO - PAULO ROGERIO DOS SANTOS GAMA", pending: 52, delivered: 67 },
            { name: "TAC CARRO - LEONARDO OLIVEIRA ATHAYDE", pending: 32, delivered: 42 },
            { name: "MEI CARRO - JOSE TALLES ARAUJO BARROS", pending: 51, delivered: 32 },
            { name: "MEI CARRO - VITORIA KAROLINY MOREIRA SANTINO", pending: 1, delivered: 29 },
            { name: "TAC CARRO - VITOR MOREIRA SANTINO", pending: 55, delivered: 20 },
            { name: "MEI CARRO - NATHALIA CRISTINA GUIDA DOS SANTOS", pending: 47, delivered: 20 },
            { name: "MEI CARRO - ERIBERGSON BEZERRA EMILIANO", pending: 20, delivered: 7 },
            { name: "TAC CARRO - JORGE BATISTA DE SOUZA", pending: 12, delivered: 2 },
            { name: "MEI CARRO - JADSON PINTO DA SILVA", pending: 1, delivered: 0 }
        ]
    },
    "SEN-GO": {
        totalPending: 186,
        totalDelivered: 243,
        totalOverall: 429,
        drivers: [
            { name: "TAC CARRO - RICARDO SILVA DE SOUSA", pending: 53, delivered: 61 },
            { name: "TAC CARRO - LUIZ EDUARDO RODRIGUES MARTINS", pending: 7, delivered: 61 },
            { name: "MEI CARRO -  FABIO JUNIO BATISTA", pending: 0, delivered: 54 },
            { name: "TAC CARRO - FREDERICO DIAS CASTRO", pending: 43, delivered: 50 },
            { name: "TAC CARRO - RAFAEL IMPERATRIZ DA SILVA", pending: 24, delivered: 17 },
            { name: "TAC CARRO - SAMUEL SILVA SANTOS", pending: 59, delivered: 0 },
            { name: "SGO -MS", pending: 439, delivered: 104 },
            { name: "MEI CARRO SGO VINICIUS FIGUEIREDO CAMPOS", pending: 93, delivered: 104 },
            { name: "MEI CARRO SGO - DAVI PAIVA VIANA", pending: 346, delivered: 0 },
            { name: "SJA -GO", pending: 468, delivered: 26 },
            { name: "TAC CARRO - ALESSANDRO PEREIRA DOS ANJOS", pending: 37, delivered: 26 },
            { name: "TAC CARRO - PEDRO VICTOR PEREIRA DO NASCIMENTO", pending: 13, delivered: 0 },
            { name: "TAC CARRO - LUCAS PEREIRA DOS SANTOS", pending: 108, delivered: 0 },
            { name: "TAC CARRO - CAIO LOPES OLIVEIRA", pending: 77, delivered: 0 },
            { name: "TAC CARRO - YAKAIO JHONNES DO CARMO OLIVEIRA", pending: 140, delivered: 0 },
            { name: "TAC CARRO - JOSIANE GONZAGA DA SILVA RESENDE", pending: 7, delivered: 0 },
            { name: "TAC CARRO - KISLEI DANILO TAVARES DE SOUSA", pending: 86, delivered: 0 }
        ]
    },
    "ANP -GO": {
        totalPending: 804,
        totalDelivered: 462,
        totalOverall: 1266,
        drivers: [
            { name: "MEI CARRO - SAMANTA ROSA SILVA PIRES", pending: 65, delivered: 77 },
            { name: "MEI CARRO - MAURICIO ANTONIO MENDONCA JUNIOR", pending: 52, delivered: 63 },
            { name: "MEI CARRO - GUSTAVO DORNELAS REGES", pending: 58, delivered: 56 },
            { name: "TAC CARRO - ROBERTO GOMES LIMA", pending: 27, delivered: 53 },
            { name: "TAC CARRO - JORGE DANIEL EVANGELISTA BUZAGLO", pending: 38, delivered: 44 },
            { name: "MEI CARRO - CAIO CESAR DA SILVA MENDES", pending: 13, delivered: 35 },
            { name: "MEI CARRO  -  ALEX ANTONIO COSTA MOREIRA", pending: 52, delivered: 33 },
            { name: "MEI CARRO - YHORRANI MACEDO COSTA", pending: 90, delivered: 32 },
            { name: "TAC CARRO - JEAN PAULO PONTES DONDE", pending: 96, delivered: 29 },
            { name: "MEI CARRO - JAQUELINE RITIELLE ROCHA SILVA", pending: 59, delivered: 22 },
            { name: "MEI CARRO - BRENO HENRIQUE DA SILVA TEIXEIRA", pending: 3, delivered: 18 },
            { name: "TAC CARRO - SHARLES RODRIGUES DA SILVA", pending: 59, delivered: 0 },
            { name: "TAC  CARRO - GLAUBER HENRIQUE CRESTANI COSTA", pending: 3, delivered: 0 },
            { name: "TAC CARRO - ADEMIR MANOEL FARIA DE OLIVEIRA", pending: 189, delivered: 0 }
        ]
    },
    "GNA -GO": {
        totalPending: 779,
        totalDelivered: 77,
        totalOverall: 856,
        drivers: [
            { name: "TAC CARRO - LUIS FERNANDO MARTINEZ CANO", pending: 21, delivered: 35 },
            { name: "MEI CARRO - ARTHUR FRANCA DE DEUS", pending: 56, delivered: 27 },
            { name: "MEI CARRO - JOAO AUGUSTO GONCALVES NETO", pending: 67, delivered: 11 },
            { name: "TAC CARRO - MARCELO BATISTA FERREIRA JUNIOR", pending: 54, delivered: 4 },
            { name: "TAC CARRO - KELLY PARREIRA DE BESSA  LOPES", pending: 6, delivered: 0 },
            { name: "TAC CARRO - ADEMIR DIAS FREIRE JUNIOR", pending: 43, delivered: 0 },
            { name: "TAC CARRO - LUAN PIRES FREITAS", pending: 65, delivered: 0 },
            { name: "TAC CARRO - MARCOS VINICIUS JUVENCIO VERAS", pending: 97, delivered: 0 },
            { name: "TAC CARRO - BRUNO HENRIQUE SILVA ROCHA", pending: 52, delivered: 0 },
            { name: "TAC CARRO - DAIANE KELLY BRAGA FERREIRA", pending: 1, delivered: 0 },
            { name: "TAC CARRO - RODRIGO ALVES VIEIRA", pending: 270, delivered: 0 },
            { name: "TAC CARRO - ELIETE DA SILVA LIBERIO", pending: 45, delivered: 0 },
            { name: "TAC CARRO - JEFERSON ROSA DOS SANTOS", pending: 2, delivered: 0 },
            { name: "GNT -MT", pending: 407, delivered: 245 },
            { name: "MEI MOTO - IVONETE DE FATIMA ZANCHETA", pending: 75, delivered: 41 },
            { name: "MEI CARRO - DERBAL FRANCISCO DA SILVA", pending: 51, delivered: 40 },
            { name: "MEI CARRO GNT AROLDO BERNADO DE SOUZA FILHO", pending: 14, delivered: 37 },
            { name: "MEI CARRO GNT ANDERSON JOSE DIDEA", pending: 42, delivered: 35 },
            { name: "MEI CARRO - LUCAS DELRIC BARBOSA DA SILVA", pending: 20, delivered: 30 },
            { name: "AGR MOTO GNT ERICA DA SILVA MEIRELES", pending: 26, delivered: 24 },
            { name: "AGR CARRO GNT MATHEUS GLOSS SILVA", pending: 22, delivered: 23 },
            { name: "MEI CARRO GNT GLEISSON HENRIQUE CABRAL DE SOUZA", pending: 11, delivered: 6 },
            { name: "AGR CARRO ALEXANDRE JUNIOR RITZKE", pending: 0, delivered: 3 },
            { name: "AGR CARRO GNT DIOGO ROSS", pending: 40, delivered: 2 },
            { name: "AGR MOTO GNT DARLEI BISPO SANTANA", pending: 0, delivered: 1 },
            { name: "AGR MOTO GNT  CRISTHIAN PEDROZO VITORINO", pending: 1, delivered: 1 },
            { name: "AGR CARRO GNT ANDRESSA ELLY RODRIGUES", pending: 0, delivered: 1 },
            { name: "AGR CARRO GNT LEANDRO DE SOUZA CARDOSO", pending: 3, delivered: 1 },
            { name: "TAC CARRO GNT RAQUEL OLIVEIRA DA SILVA", pending: 102, delivered: 0 },
            { name: "GUA -DF", pending: 216, delivered: 280 },
            { name: "MEI CARRO - RAFAEL VILLACHAN DAMASCENO", pending: 16, delivered: 65 },
            { name: "MEI CARRO - EMANUEL VICTOR MONTEIRO FONSECA", pending: 65, delivered: 63 },
            { name: "MEI CARRO - NIVALDO BUENO DOS SANTOS", pending: 1, delivered: 56 },
            { name: "MEI CARRO - LEONARDO GOMES DOS REIS", pending: 1, delivered: 34 },
            { name: "MEI CARRO - ELIO COTEGIPE MIRANDA SILVA", pending: 31, delivered: 23 },
            { name: "MEI CARRO - JOSE DOMINGOS DOURADO VIANA", pending: 0, delivered: 19 },
            { name: "MEI CARRO - GLEISSON FERREIRA DOS SANTOS", pending: 25, delivered: 12 },
            { name: "TAC CARRO - ELTON ANTONIO PACHECO LIMA", pending: 7, delivered: 8 },
            { name: "MEI CARRO - RAIANE LEITE OLIVEIRA", pending: 70, delivered: 0 }
        ]
    },
    "IPR -GO": {
        totalPending: 0,
        totalDelivered: 1,
        totalOverall: 1,
        drivers: [
            { name: "TAC CARRO -  IVAN CAETANO DA ROCHA", pending: 0, delivered: 1 }
        ]
    },
    "PRG -GO": {
        totalPending: 204,
        totalDelivered: 3,
        totalOverall: 207,
        drivers: [
            { name: "TAC CARRO - DEBORA KARLA MENEZES DE JESUS", pending: 127, delivered: 3 },
            { name: "TAC CARRO - NAIARA CAROLYNE OLIVEIRA", pending: 16, delivered: 0 },
            { name: "TAC CARRO - GABRIEL BATISTA DUARTE", pending: 57, delivered: 0 },
            { name: "MEI CARRO - WILLYAN RODOVAL DA SILVA", pending: 1, delivered: 0 },
            { name: "MEI CARRO - MATHEUS CAVALCANTE PEREIRA", pending: 3, delivered: 0 },
            { name: "PTD -MT", pending: 172, delivered: 117 },
            { name: "TAC CARRO PTD ELIZEU FERREIRA KUSTHER", pending: 1, delivered: 54 },
            { name: "TAC CARRO PTD BETANIA COSTA ALECRIM", pending: 2, delivered: 42 },
            { name: "TAC MOTO MDT CALEB ALBAREZ FERNANDES", pending: 1, delivered: 10 },
            { name: "TAC CARRO PTD FATIMA DE OLIVEIRA LEANDRO", pending: 1, delivered: 6 },
            { name: "TAC CARRO VALDO OLIVEIRA KUSTHER", pending: 0, delivered: 3 },
            { name: "TAC MOTO PTD RAYANE ALVEZ PEREIRA", pending: 35, delivered: 1 },
            { name: "TAC CARRO PTD MARISANDRO MARLON R DE OLIVEIRA", pending: 91, delivered: 1 },
            { name: "TAC CARRO PTD NILTOM DE SOUZA SANTOS", pending: 1, delivered: 0 },
            { name: "TAC CARRO PTD EMANOEL DHANATAS SILVA SANTO", pending: 3, delivered: 0 },
            { name: "TAC CARRO ROBERTO PEREIRA DOS SANTOS", pending: 36, delivered: 0 },
            { name: "TAC CARRO PTD GESSICA ROGERIO", pending: 1, delivered: 0 },
            { name: "PVH -RO", pending: 3692, delivered: 1155 },
            { name: "MEI CARRO MAYKON JONATAN BERMUD", pending: 6, delivered: 97 },
            { name: "TAC CARRO MAGNO RIBEIRO TOLEDO", pending: 53, delivered: 87 },
            { name: "TAC CARRO FRANCISCO VALMIR DA SILVA", pending: 65, delivered: 77 },
            { name: "MEI CARRO UELISSON DIOGO DE MEDEIROS SILVA", pending: 76, delivered: 71 },
            { name: "MEI CARRO RAIMUNDA DE AZEVEDO ARAUJO", pending: 63, delivered: 71 },
            { name: "MEI CARRO DOUGLAS RANIELY PASSOS GONCALVES", pending: 53, delivered: 69 },
            { name: "MEI CARRO ELIELSON PEREIRA MARTINS", pending: 90, delivered: 67 },
            { name: "MEI CARRO RONALD MONTEIRO SOARES", pending: 21, delivered: 60 },
            { name: "TAC CARRO EDNA MARIA BATISTA", pending: 44, delivered: 59 },
            { name: "TAC CARRO OLAVO DE OLIVEIRA MORAIS", pending: 0, delivered: 59 },
            { name: "MEI CARRO MARCO ANTONIO DA SILVA ROSA JUNIOR", pending: 0, delivered: 57 },
            { name: "TAC CARRO ADLER ALVES DE MELO RODRIGUES", pending: 229, delivered: 45 },
            { name: "TAC CARRO GIOVANNA STEFANY DE SOUZA COELHO LIMA", pending: 35, delivered: 43 },
            { name: "TAC CARRO LUSVANIA BELARMINO NOGUEIRA DE FARIAS", pending: 40, delivered: 39 },
            { name: "ETC CARRO ANDRESSA - ADRIANA OLIVEIRA PENHA", pending: 38, delivered: 37 },
            { name: "MEI CARRO ALEXANDRE VASCONCELOS DE MORAES", pending: 27, delivered: 34 },
            { name: "MEI CARRO LUCAS MACHADO THOMAS", pending: 63, delivered: 33 },
            { name: "TAC CARRO EMELIN SANTOS BARBOSA DE SOUZA", pending: 67, delivered: 32 },
            { name: "MEI CARRO LUCAS PEREIRA SILVA", pending: 23, delivered: 28 },
            { name: "TAC CARRO JUNIOR DE OLIVEIRA", pending: 56, delivered: 21 },
            { name: "MEI CARRO FRANCISCO DE SOUSA FREITAS", pending: 32, delivered: 17 },
            { name: "MEI CARRO UELTON RAMOS DA SILVA", pending: 25, delivered: 15 },
            { name: "MEI CARRO MAYCON DOUGLAS DE ASSIS MENEZES", pending: 97, delivered: 14 },
            { name: "TAC CARRO LUANA DANTAS DE BRITO", pending: 55, delivered: 13 },
            { name: "AGR CARRO ANA LUMA CALDAS ALMEIDA", pending: 34, delivered: 9 },
            { name: "MEI CARRO HELDON CARLOS AZEVEDO SILVA", pending: 286, delivered: 1 },
            { name: "AGR ETC CARRO MARCOS ANTONIO VIEIRA DE AZEVEDO", pending: 202, delivered: 0 },
            { name: "TAC CARRO SIDNEI LOPES DA SILVA JUNIOR", pending: 77, delivered: 0 },
            { name: "TAC CARRO ROMULO DA SILVA MACHADO", pending: 141, delivered: 0 },
            { name: "MEI CARRO ALISSON MACEDO GONCALVES", pending: 78, delivered: 0 },
            { name: "MEI CARRO JULIANE FERREIRA DA ROCHA", pending: 62, delivered: 0 },
            { name: "AGR MEI CARRO JACSON HENRIQUE ROSA", pending: 113, delivered: 0 },
            { name: "MEI CARRO KELVIN LUCAS FERREIRA DA CRUZ", pending: 123, delivered: 0 },
            { name: "MEI CARRO PAULO CEZAR MARQUES DE OLIVEIRA", pending: 106, delivered: 0 },
            { name: "AGR ETC CARRO MARCOS ALVES DA SILVA", pending: 121, delivered: 0 },
            { name: "TAC CARRO ROSINALDO ANDRADE DA SILVA", pending: 109, delivered: 0 },
            { name: "MEI CARRO MARLY LUIZ DOS SANTOS", pending: 704, delivered: 0 },
            { name: "TAC MOTO DANILO FERREIRA DAVI", pending: 14, delivered: 0 },
            { name: "MEI CARRO JOAO KLEBER MARQUES NASCIMENTO", pending: 180, delivered: 0 },
            { name: "MEI CARRO JOSE DELSON RIBEIRO", pending: 84, delivered: 0 },
            { name: "PVL -MT", pending: 1237, delivered: 121 },
            { name: "TAC CARRO PVL TEREZINHA MACHADO", pending: 55, delivered: 28 },
            { name: "TAC CARRO PVL MARCELO BATISTA LAURINDO", pending: 38, delivered: 21 },
            { name: "TAC CARRO PVL PAULO DE SOUZA GONÇALVES", pending: 8, delivered: 18 },
            { name: "MEI CARRO PVL ALEX MACEDO DA SILVA", pending: 57, delivered: 17 },
            { name: "TAC CARRO - Rogério Silva da Rocha", pending: 35, delivered: 15 },
            { name: "TAC CARRO PVL RAFAEL OLIVEIRA DE PAULA", pending: 5, delivered: 13 },
            { name: "TAC CARRO PVL FERNANDO FERREIRA DE OLIVEIRA", pending: 72, delivered: 7 },
            { name: "MEI CARRO PVL CHRISTYAN SOBRINHO FERREIRA ABREU", pending: 7, delivered: 1 },
            { name: "TAC CARRO BGA PATRICIA SOUSA DA SILVA", pending: 17, delivered: 1 },
            { name: "TAC CARRO PVL CLEBERSON DOS SANTOS CONCEICÃO", pending: 39, delivered: 0 },
            { name: "TAC CARRO PVL MONICA VIENA ALVES", pending: 61, delivered: 0 },
            { name: "MEI CARRO PVL LUCIANO DA SILVA", pending: 1, delivered: 0 },
            { name: "TAC MOTO PVL CARLOS EDUARDO DOS SANTOS CARDOSO", pending: 50, delivered: 0 },
            { name: "TAC CARRO PVL MAURIDES MANOEL DE LIMA", pending: 30, delivered: 0 },
            { name: "TAC MOTO PVL GILSON ANDRADE DA SILVA", pending: 53, delivered: 0 },
            { name: "MEI CARRO PVL RENATA SIMONE NEVES DORNELAS", pending: 32, delivered: 0 },
            { name: "ETC CARRO - JOAO ANTONIO DA FONSECA", pending: 87, delivered: 0 },
            { name: "TAC CARRO - ROSELY MACIEL DE SOUZA", pending: 114, delivered: 0 },
            { name: "TAC CARRO PVL LEONARDO DOS SANTOS", pending: 114, delivered: 0 },
            { name: "TAC CARRO PVL LIANA SOUSA MENESES", pending: 114, delivered: 0 },
            { name: "TAC MOTO PVL WESLEY MARTINS MARQUES", pending: 79, delivered: 0 },
            { name: "TAC CARRO PVL JULIANO PIRES", pending: 84, delivered: 0 },
            { name: "TAC CARRO PVL LAZARA ALVES DE SOUZA", pending: 85, delivered: 0 }
        ]
    },
    "SMA -GO": {
        totalPending: 0,
        totalDelivered: 0,
        totalOverall: 0,
        drivers: [
        ]
    },
    "SMB -GO": {
        totalPending: 581,
        totalDelivered: 0,
        totalOverall: 581,
        drivers: [
            { name: "TAC CARRO - JOELTON ROSA DE OLIVEIRA", pending: 118, delivered: 0 },
            { name: "TAC CARRO - CLAUDIANE GOMES DE ALMEIDA", pending: 60, delivered: 0 },
            { name: "TAC CARRO - OSVALDIR NUNES DA SILVA", pending: 43, delivered: 0 },
            { name: "MEI CARRO - MAYARA BRANDAO PEREIRA", pending: 40, delivered: 0 },
            { name: "TAC CARRO - GREICE KELY LOPES BOTELHO", pending: 174, delivered: 0 },
            { name: "MEI CARRO - WALLACE HENRIQUE FERREIRA MACEDO", pending: 5, delivered: 0 },
            { name: "TAC CARRO - LUZIMAR PEREIRA DE AGUIAR", pending: 26, delivered: 0 },
            { name: "TAC BICICLETA - JENNYFER GONCALVES DA SILVA", pending: 9, delivered: 0 },
            { name: "MEI CARRO - JOICY CAMILA GOMIDES", pending: 98, delivered: 0 },
            { name: "TAC CARRO - ANITAIR GOMES DA SILVA", pending: 8, delivered: 0 },
            { name: "SMD -AC", pending: 257, delivered: 402 },
            { name: "MEI MOTO ANTONIO MARCIO OLIVEIRA DE MEDEIRO", pending: 7, delivered: 183 },
            { name: "TAC CARRO - RICHARD CORDEIRO DA SILVA", pending: 96, delivered: 134 },
            { name: "MEI CARRO RICARDO CESAR COSTA DA SILVA", pending: 150, delivered: 84 },
            { name: "TAC MOTO SUELEN CRISTINA DA SILVA PINTO DIAS", pending: 4, delivered: 1 },
            { name: "SNP -MT", pending: 38, delivered: 244 },
            { name: "TAC CARRO SNP LUCAS GABRIEL DE ALMEIDA", pending: 2, delivered: 47 },
            { name: "MEI CARRO SNP EVAELTON DE AMORIM", pending: 20, delivered: 45 },
            { name: "TAC CARRO SNP ANTÔNIO MIGUEL CAMARGO", pending: 1, delivered: 42 },
            { name: "TAC CARRO SNP ITAMAR LOPES VELOSO", pending: 1, delivered: 42 },
            { name: "TAC CARRO SNP WELLYTON DA SILVA", pending: 10, delivered: 31 },
            { name: "TAC CARRO SNP IGOR SILVA MARTINS", pending: 0, delivered: 21 },
            { name: "TAC CARRO SNP THIAGO JOSE DE AZEVEDO", pending: 1, delivered: 14 },
            { name: "MEI CARRO SNP TATIANE DE OLIVEIRA SANTOS", pending: 0, delivered: 2 },
            { name: "TAC MOTO SNP ODIRLEI ZAROSSI", pending: 2, delivered: 0 },
            { name: "TAC CARRO SNP JULIUS CESAR DOS SANTOS ALVES", pending: 1, delivered: 0 },
            { name: "SRS -MT", pending: 364, delivered: 205 },
            { name: "TAC CARRO  LUIS MARCOS SILVA CORREA", pending: 53, delivered: 76 },
            { name: "TAC CARRO SRS LEANDRO SOUZA BEZERRA", pending: 2, delivered: 63 },
            { name: "TAC CARRO SRS JOSÉ FRANCISCO DA SILVA VERAS", pending: 74, delivered: 58 },
            { name: "TAC CARRO SRS ANTONIO JUCELINO MARQUES CARDOSO", pending: 106, delivered: 8 },
            { name: "TAC CARRO SRS ALESSANDRA FERREIRA TAVARES", pending: 8, delivered: 0 },
            { name: "TAC CARRO SRS JENIFER LARA COSTA CERUTTI", pending: 77, delivered: 0 },
            { name: "TAC CARRO SRS SAMUEL LOUREÇO DE LIMA", pending: 17, delivered: 0 },
            { name: "TAC CARRO SRS IVONE TIEPO", pending: 11, delivered: 0 },
            { name: "CD BASE SRS01", pending: 9, delivered: 0 },
            { name: "TAC CARRO SRS EVANILDO MELO PANTOJA", pending: 7, delivered: 0 },
            { name: "TGA -MT", pending: 1635, delivered: 149 },
            { name: "TAC CARRO TGA DENILSON MATIAS DA SILVA", pending: 1, delivered: 40 },
            { name: "TAC CARRO  TGA CRISLANE MANOELA DA SILVA", pending: 39, delivered: 23 },
            { name: "TAC CARRO - JOSE NILTON ALMEIDA LIMA", pending: 72, delivered: 20 },
            { name: "TAC CARRO FABIANA PAULINO MARTINS", pending: 59, delivered: 20 },
            { name: "TAC CARRO - WESLLEY DHENNER DA SILVA COSTA", pending: 92, delivered: 15 },
            { name: "TAC CARRO - TATYNARA CRISTINA SANTOS PUKA", pending: 83, delivered: 9 },
            { name: "TAC CARRO TGA ROBSON SANTOS ROSSI", pending: 56, delivered: 8 },
            { name: "TAC CARRO TGA FABIO DE SOUZA DIAS", pending: 50, delivered: 8 },
            { name: "TAC CARRO TGA RICHARD TUTIACHI DA SILVA", pending: 87, delivered: 6 },
            { name: "TAC CARRO TGA DOUGLAS SANTOS MARTINS", pending: 8, delivered: 0 },
            { name: "TAC CARRO TGA DELISE APARECIDA DE SOUZA CORRERIA", pending: 13, delivered: 0 },
            { name: "TAC CARRO TGA FRANCISCO CARDOZO SANTANA", pending: 19, delivered: 0 },
            { name: "TAC CARRO TGA RONALDO JOSE DA SILVA", pending: 57, delivered: 0 },
            { name: "TAC CARRO - Jorge dos Santos Oliveira", pending: 200, delivered: 0 },
            { name: "TAC CARRO TGA MARIA CINTIA MENDES DE SOUZA", pending: 12, delivered: 0 },
            { name: "TAC CARRO - GUSTAVO HENRIQUE DECOL DO NASCIMENTO", pending: 128, delivered: 0 },
            { name: "TAC CARRO - MATHEUS FERREIRA LEMES", pending: 54, delivered: 0 },
            { name: "TAC CARRO - STEPHANIE DE OLIVEIRA LEANDRO", pending: 102, delivered: 0 },
            { name: "TAC CARRO TGA ANDRESSA ROSA DE PIERRI", pending: 59, delivered: 0 },
            { name: "TAC CARRO TGA WAGNER COSTA  ALVES", pending: 38, delivered: 0 },
            { name: "TAC CARRO - DEBORA DE ALMEIDA SOUSA", pending: 71, delivered: 0 },
            { name: "MEI CARRO TGA LUANA CAROLINA OLIVEIRA CORNIANI", pending: 69, delivered: 0 },
            { name: "TAC MOTO TGA WEVERTON CLEBER MONTEIRO", pending: 39, delivered: 0 },
            { name: "TAC CARRO TGA ALEXIA LIMA MENDES", pending: 109, delivered: 0 },
            { name: "TAC CARRO TGA AMANDA MARTINS SILVA", pending: 118, delivered: 0 },
            { name: "TGT -DF", pending: 562, delivered: 586 },
            { name: "MEI CARRO - EDUARDO LOURENCO BARROSO", pending: 9, delivered: 101 },
            { name: "MEI CARRO - SANDRA MARA PEREIRA PINTO", pending: 148, delivered: 100 },
            { name: "MEI CARRO - NADINE SEVERINO GOMES", pending: 176, delivered: 99 },
            { name: "MEI CARRO - JOSE UILSON CATARINO DA SILVA", pending: 20, delivered: 81 },
            { name: "MEI CARRO - LUCAS FERREIRA VIDAL", pending: 13, delivered: 79 },
            { name: "MEI CARRO - CLEBER EUSTAQUIO DE JESUS", pending: 43, delivered: 62 },
            { name: "TAC CARRO - NARDEL DOS SANTOS SOUSA", pending: 21, delivered: 55 },
            { name: "MEI CARRO - CARLIANNI RONDON BOLIVAR", pending: 132, delivered: 9 },
            { name: "TLL -MS", pending: 283, delivered: 20 },
            { name: "MOTO TAC DOUGLAS ANTONIO ALVES RIBEIRO", pending: 1, delivered: 14 },
            { name: "TAC MOTO VALQUIRIA FREITAS MACIEL", pending: 66, delivered: 3 },
            { name: "CARRO TAC BRUNA BARCELOS QUEIROZ", pending: 0, delivered: 2 },
            { name: "TAC CARRO Luiz Carlos Teles de Souza", pending: 0, delivered: 1 },
            { name: "TAC CARRO MARISA SOARES LOPES", pending: 135, delivered: 0 },
            { name: "CARRO TAC MAIKON DA SILVA WOLF", pending: 80, delivered: 0 },
            { name: "TAC MOTO ITAMAR BORGES FERREIRA", pending: 1, delivered: 0 }
        ]
    },
    "URC -GO": {
        totalPending: 1546,
        totalDelivered: 180,
        totalOverall: 1726,
        drivers: [
            { name: "MEI CARRO - MARCIO KENNEDY RODRIGUES GOMES", pending: 28, delivered: 45 },
            { name: "TAC MOTO - ALESSANDRO ANTUNES DA SILVA", pending: 24, delivered: 42 },
            { name: "MEI CARRO - LUZIA FRANCISCO OZORIO SANTOS", pending: 76, delivered: 40 },
            { name: "MEI CARRO - TASSIO VINICIUS SANTOS BRANDAO", pending: 347, delivered: 31 },
            { name: "TAC CARRO - RODRIGO RIBEIRO SILVA LEITE", pending: 26, delivered: 22 },
            { name: "TAC CARRO - PATRICIA MARA DE OLIVEIRA", pending: 138, delivered: 0 },
            { name: "TAC CARRO - MARCELO COSTA SILVA", pending: 97, delivered: 0 },
            { name: "TAC CARRO - DIVINO CARLOS DA SILVA", pending: 58, delivered: 0 },
            { name: "TAC CARRO - EDER RODRIGUES DA SILVA", pending: 44, delivered: 0 },
            { name: "TAC CARRO - MARCELO LISBOA PARREIRA", pending: 87, delivered: 0 },
            { name: "TAC CARRO - RODRIGO LUIZ VICENTE", pending: 34, delivered: 0 },
            { name: "TAC CARRO - ROBSON MARCIANO DA SILVA", pending: 29, delivered: 0 },
            { name: "TAC CARRO - ANTONIO CARLOS VIEIRA DA SILVA", pending: 85, delivered: 0 },
            { name: "TAC CARRO - JOAO RAMOS DE ALBUQUERQUE", pending: 130, delivered: 0 },
            { name: "MEI CARRO - CASSIO CARVALHO DA SILVA", pending: 41, delivered: 0 },
            { name: "TAC CARRO - EMERSON CAMPOS PIMENTEL", pending: 301, delivered: 0 },
            { name: "TAC CARRO - EVERLAM NOVAES DE CARVALHO", pending: 1, delivered: 0 },
            { name: "VGR 02-MT", pending: 454, delivered: 9 },
            { name: "MEI CARRO VGR RONAIR JOSE DE PAULA", pending: 17, delivered: 9 },
            { name: "MEI CARRO VGR JOZICLEI LIMA DA SILVA", pending: 164, delivered: 0 },
            { name: "TAC CARRO VGR JOAO PEDRO ROSA SILVA", pending: 2, delivered: 0 },
            { name: "TAC CARRO VGR EOCIONEY LUIS CINTRA DE OLIVEIRA", pending: 35, delivered: 0 },
            { name: "MEI CARRO VGR LEANDRO ALVES PORTO", pending: 58, delivered: 0 },
            { name: "TAC CARRO VGR JOZINEI SANTOS DA SILVA", pending: 54, delivered: 0 },
            { name: "TAC CARRO VGR MARIO GOMES DE CAMPOS", pending: 12, delivered: 0 },
            { name: "TAC CARRO VGR MAXUEL GONCALVES FERREIRA", pending: 40, delivered: 0 },
            { name: "MEI CARRO VGR JOSIANE SILVA DE OLIVEIRA MONTEIRO", pending: 71, delivered: 0 },
            { name: "TAC CARRO - Patrícia da Silva Costa", pending: 1, delivered: 0 },
            { name: "VGR-MT", pending: 359, delivered: 45 },
            { name: "TAC CARRO  - WILLY BISPO NASCIMENTO", pending: 7, delivered: 26 },
            { name: "TAC CARRO VGR  JEKSON ALBUQUERQUE SHELID", pending: 54, delivered: 9 },
            { name: "TAC CARRO VGR KATRYNE PEDROSO DOS SANTOS", pending: 36, delivered: 6 },
            { name: "TAC CARRO VGR KENIO DE ARRUDA", pending: 84, delivered: 4 },
            { name: "TAC CARRO VGR JONATHAN GERALDO DE ALCANTARA", pending: 56, delivered: 0 },
            { name: "TAC CARRO VGR JULIANO FERREIRA ROSA", pending: 54, delivered: 0 },
            { name: "TAC CARRO - Valdeyse Josyhellen Marçal", pending: 13, delivered: 0 },
            { name: "TAC MOTO VGR VIVIANE MARIA DA SILVA SANTOS", pending: 8, delivered: 0 },
            { name: "MEI CARRO VGR THAISON SANTOS SOUZA", pending: 1, delivered: 0 },
            { name: "TAC CARRO VGR CLEITON CAMPOS DAVI", pending: 46, delivered: 0 },
            { name: "VHL-RO", pending: 245, delivered: 67 },
            { name: "TAC CARRO ALANA MAYARA MARQUEZIN", pending: 2, delivered: 33 },
            { name: "TAC CARRO ALEXANDRE FERREIRA FONSECA OSORIO", pending: 0, delivered: 12 },
            { name: "AGR MEI CARRO RAYANA MONTEIRO GOMES", pending: 28, delivered: 10 },
            { name: "TAC CARRO HONORIO ROBERTO DE MOURA", pending: 13, delivered: 5 },
            { name: "TAC CARRO AYNARA FERREIRA DA CRUZ", pending: 15, delivered: 4 },
            { name: "TAC CARRO ELAINE SOUZA GONCALVES ALVES", pending: 164, delivered: 1 },
            { name: "TAC CARRO MANOEL MESSIAS MENDES DA SILVA PINHEIRO", pending: 0, delivered: 1 },
            { name: "TAC CARRO GUILHERME COSTA RODRIGUES SORDI MOREIRA", pending: 0, delivered: 1 },
            { name: "TAC CARRO JULIANE DE MORAES BACH DA SILVA", pending: 1, delivered: 0 },
            { name: "TAC CARRO ANDRE APARECIDO MAQUIELE DE ANDRADE", pending: 5, delivered: 0 },
            { name: "TAC CARRO DIANA LOPES DA SILVA", pending: 17, delivered: 0 },
            { name: "VLP -GO", pending: 400, delivered: 360 },
            { name: "MEI CARRO - GILSON SYLVIO DA FONSECA", pending: 8, delivered: 94 },
            { name: "MEI CARRO - CONCEICAO DE MARIA SOUSA GOMES", pending: 37, delivered: 74 },
            { name: "MEI CARRO - HENRIQUE PORTELA DO NASCIMENTO", pending: 45, delivered: 66 },
            { name: "MEI CARRO - WILLIAM DE OLIVEIRA PESSOA", pending: 101, delivered: 63 },
            { name: "TAC CARRO - EDIENE GOMES FERNANDES", pending: 6, delivered: 47 },
            { name: "TAC CARRO - GABRIEL NUNES BASILIO", pending: 83, delivered: 8 },
            { name: "MEI CARRO - RODRIGO ROCHA DE SOUSA BATISTA", pending: 120, delivered: 8 },
            { name: "Total Geral", pending: 41182, delivered: 16766 }
        ]
    }
};
