const allDashboardData = {
    "Geral": {
        totalPending: 0,
        totalDelivered: 0,
        totalOverall: 0,
        drivers: [
        ]
    },
    "APG -GO": {
        totalPending: 529,
        totalDelivered: 111,
        totalOverall: 640,
        drivers: [
            { name: "MEI CARRO - KETHELLEN KAROLAYNE B. DO NASCIMENTO", pending: 45, delivered: 45 },
            { name: "MEI CARRO - Luiz Alberto Bueno da Silva", pending: 23, delivered: 37 },
            { name: "TAC CARRO - MILUQUINO COSTA PINTO JUNIOR", pending: 55, delivered: 23 },
            { name: "TAC CARRO - SAMUEL MARTINS FERREIRA", pending: 89, delivered: 4 },
            { name: "TAC CARRO - MICHELE DA COSTA REZENDE", pending: 59, delivered: 1 },
            { name: "MEI CARRO - SANTHIAGO CANDIDO SILVA ALVES", pending: 10, delivered: 1 },
            { name: "MEI CARRO - VINICIUS JUNIO DE MENDONCA", pending: 74, delivered: 0 },
            { name: "MEI CARRO - MATHEUS SAMPAIO DOS SANTOS", pending: 99, delivered: 0 },
            { name: "CARRO TAC - JAIME XISTO DE SANTANA", pending: 74, delivered: 0 },
            { name: "MEI CARRO - RICHARD DAMACENA DE OLIVEIRA", pending: 1, delivered: 0 },
            { name: "AQD -MS", pending: 237, delivered: 50 },
            { name: "MEI MOTO AQD JANSLIEL LEAO DA SILVA", pending: 155, delivered: 50 },
            { name: "MEI CARRO AQD FERNANDO DA SILVA BARBOSA OLIVEIRA", pending: 82, delivered: 0 },
            { name: "ARI -MT", pending: 273, delivered: 7 },
            { name: "TAC CARRO ARI MYCAELLA LORENA DA COSTA NUNES", pending: 2, delivered: 5 },
            { name: "TAC CARRO ARI POLYANA OLIVEIRA PRADO", pending: 1, delivered: 2 },
            { name: "TAC CARRO ARI TIAGO DE SOUZA LUCENA", pending: 100, delivered: 0 },
            { name: "TAC CARRO ARI  CARLOS DANIEL CARDOSO", pending: 21, delivered: 0 },
            { name: "MEI CARRO ARI GENIVALDO CARLOS VIEIRA", pending: 149, delivered: 0 },
            { name: "ARQ -RO", pending: 2580, delivered: 78 },
            { name: "TAC CARRO WERLES DA SILVA CANDIDO", pending: 92, delivered: 31 },
            { name: "MEI CARRO LUCAS SILVA PEREIRA DOS SANTOS", pending: 207, delivered: 29 },
            { name: "TAC CARRO ANA CAROLINA DIEDRICH DE ALMEIDA", pending: 103, delivered: 15 },
            { name: "MEI CARRO ELIZA LOPES DALLA COSTA", pending: 676, delivered: 2 },
            { name: "TAC CARRO JOSE MARCIO SANTOS", pending: 70, delivered: 1 },
            { name: "TAC CARRO EDVALDO OLIVEIRA AUGUSTO", pending: 50, delivered: 0 },
            { name: "MEI CARRO DHIONES RIKER OLIVEIRA", pending: 458, delivered: 0 },
            { name: "TAC CARRO WELLITON FERREIRA ALMEIDA", pending: 69, delivered: 0 },
            { name: "MEI CARRO THIAGO DE PAULA SILVA", pending: 375, delivered: 0 },
            { name: "TAC CARRO GLEICIANE FERREIRA TORRES DO PRADO", pending: 45, delivered: 0 },
            { name: "MEI CARRO VALDECI MORAES JUNIOR", pending: 221, delivered: 0 },
            { name: "TAC CARRO ROSIVALDO MARINHO DE ANDRADE", pending: 8, delivered: 0 },
            { name: "MEI CARRO ANA PAULA DA SILVA FERREIRA", pending: 87, delivered: 0 },
            { name: "MEI CARRO EDMAR APARECIDO COSTA", pending: 29, delivered: 0 },
            { name: "TAC CARRO BRUNO GABRIEL DE SOUZA PIRES", pending: 69, delivered: 0 },
            { name: "TAC CARRO CARLOS CALDEIRA LORENZETTI", pending: 21, delivered: 0 },
            { name: "ATF -MT", pending: 11, delivered: 22 },
            { name: "TAC MOTO ATF GUILHERME DE ALMEIDA MOREIRA", pending: 0, delivered: 18 },
            { name: "TAC CARRO ATF ADEMILTON ROFRIGUES DE SOUZA", pending: 0, delivered: 2 },
            { name: "TAC CARRO ATF ALESSANDRA KRETSCHMER", pending: 0, delivered: 1 },
            { name: "TAC CARRO ATF CHARLES ALEXANDRE LOURENÇO", pending: 0, delivered: 1 },
            { name: "TAC MOTO ATF JOELSON CASTILHO DE SOUZA", pending: 9, delivered: 0 },
            { name: "TAC CARRO ATF EDGAR DE MEDEIROS ROCHA", pending: 2, delivered: 0 },
            { name: "BGA -MT", pending: 12, delivered: 19 },
            { name: "TAC CARRO BGA LARYSSA DE OLIVEIRA ROSA", pending: 9, delivered: 19 },
            { name: "MEI MOTO BGA ROBERTO PIRES DA SILVA", pending: 3, delivered: 0 },
            { name: "BSB -DF", pending: 1416, delivered: 450 },
            { name: "MEI CARRO - NELSON CORDEIRO DE ARAUJO JUNIOR", pending: 125, delivered: 68 },
            { name: "TAC CARRO - CLOVIS RAMALHO PEREIRA", pending: 41, delivered: 55 },
            { name: "MEI CARRO - JOSIMAR DANIEL DOMINGOS", pending: 35, delivered: 45 },
            { name: "MEI CARRO - ELIDA FERREIRA MAIA", pending: 69, delivered: 33 },
            { name: "TAC CARRO - REGINALDO DA SILVA ROCHA", pending: 82, delivered: 27 },
            { name: "TAC MOTO - JAIR DO CARMO TOLEDO", pending: 66, delivered: 27 },
            { name: "TAC CARRO - ELEN SORAYA DE OLIVEIRA CARDOSO", pending: 41, delivered: 27 },
            { name: "MEI CARRO - MICAEL PEREIRA DE MELO SILVA", pending: 11, delivered: 26 },
            { name: "MEI CARRO - GILSON LOPES DE SOUZA", pending: 133, delivered: 23 },
            { name: "TAC CARRO - JOSE COELHO ROCHA FILHO", pending: 60, delivered: 20 },
            { name: "TAC CARRO - GEOVAN NUNES RODRIGUES", pending: 39, delivered: 20 },
            { name: "MEI CARRO - DALMISON ALVES DE SOUZA", pending: 75, delivered: 19 },
            { name: "TAC CARRO - JOAO SANTANA GUERRA NETO", pending: 93, delivered: 19 },
            { name: "TAC CARRO - WELERSON RIBEIRO DOS SANTOS", pending: 86, delivered: 15 },
            { name: "TAC CARRO - WALLYSON MICHAEL GONCALVES DA ROCHA", pending: 55, delivered: 15 },
            { name: "MEI CARRO - WEVERSON DOS SANTOS FERREIRA", pending: 90, delivered: 11 },
            { name: "MEI CARRO - ROGERIO DE ARAUJO BENIGNO", pending: 122, delivered: 0 },
            { name: "TAC CARRO - GABRIEL DOS SANTOS COUTO", pending: 193, delivered: 0 }
        ]
    },
    "CAN -GO": {
        totalPending: 22,
        totalDelivered: 1,
        totalOverall: 23,
        drivers: [
            { name: "TAC CARRO - PEDRO HENRIQUE MARQUES DE PAULA", pending: 2, delivered: 1 },
            { name: "TAC CARRO - VIVIANI SAIARA DE SOUZA", pending: 2, delivered: 0 },
            { name: "TAC CARRO - ALEX DIAS DA SILVA", pending: 16, delivered: 0 },
            { name: "TAC CARRO - CARLOS RENATO ALVES PEDROSO SOARES", pending: 2, delivered: 0 },
            { name: "CCR -MT", pending: 579, delivered: 37 },
            { name: "TAC CARRO CCR JEFERSON ADRIANO BRITO DOS SANTOS", pending: 87, delivered: 21 },
            { name: "TAC CARRO CCR MARCELO DELUQUI DA SILVA", pending: 163, delivered: 10 },
            { name: "TAC CARRO ADEJUNIO CAMARGO DOS SANTOS", pending: 15, delivered: 5 },
            { name: "TAC CARRO CCR RONILSON CELESTE DUARTE DE SOUZA", pending: 149, delivered: 1 },
            { name: "TAC CARRO CCR HEITOR CARNEIRO ALVES", pending: 91, delivered: 0 },
            { name: "TAC CARRO CCR JOSE MATHEUS GONÇALVES MIRANDA", pending: 74, delivered: 0 },
            { name: "CEIN -DF", pending: 188, delivered: 57 },
            { name: "TAC CARRO - EMANOEL RAPHAEL DE ARAUJO MAGALHAES", pending: 20, delivered: 31 },
            { name: "MEI CARRO - EMANOELA ARAUJO CAVALCANTE", pending: 55, delivered: 26 },
            { name: "TAC CARRO - MANOEL COSTA CAVALCANTE NETO", pending: 88, delivered: 0 },
            { name: "MEI CARRO - ALLAN JACKSON CORREA DOS SANTOS", pending: 25, delivered: 0 },
            { name: "CEIS -DF", pending: 68, delivered: 110 },
            { name: "MEI CARRO - KELLY LUANE PEREIRA SOARES", pending: 20, delivered: 63 },
            { name: "MEI CARRO - LUIZ ANTONIO RAMALHO DA CUNHA", pending: 48, delivered: 47 },
            { name: "CGB 02-MT", pending: 340, delivered: 160 },
            { name: "MEI CARRO CGB HIGOR MATHEUS AMARANTE THOME", pending: 98, delivered: 46 },
            { name: "TAC CARRO CGB LEO CRECIO DE FARIA", pending: 58, delivered: 44 },
            { name: "TAC CARRO CGB VAGNER BATISTA CERQUEIRA", pending: 34, delivered: 33 },
            { name: "TAC CARRO CGB IOLANDA PARREIRA EREGIPE", pending: 55, delivered: 14 },
            { name: "TAC CARRO JACSON DOUGLAS OLIVEIRA DE SOUZA", pending: 41, delivered: 12 },
            { name: "TAC CARRO CGB ADEILTON DA SILVA MORAES", pending: 51, delivered: 11 },
            { name: "TAC CARRO CGB JESSIKA ALINE FERNANDES DIAS", pending: 3, delivered: 0 },
            { name: "CGB 03-MT", pending: 414, delivered: 356 },
            { name: "TAC CARRO CGB  MARCELO NEVES", pending: 64, delivered: 64 },
            { name: "TAC CARRO CGB  GRAZIANI BENEDITO DA SILVA", pending: 17, delivered: 62 },
            { name: "TAC CARRO CGB LEONEL BENEDITO DE SOUZA ALMEIDA", pending: 25, delivered: 52 },
            { name: "TAC CARRO - Thiago Moreira da Silva", pending: 30, delivered: 48 },
            { name: "TAC CARRO CGB JAQUELINE REGINA PINHO DA COSTA", pending: 22, delivered: 31 },
            { name: "MEI CARRO CGB MICHELE ASSUNÇÃO PINHEIRO DE MOURA", pending: 0, delivered: 28 },
            { name: "TAC CARRO CGB DANILO RODRIGUES MARCELO", pending: 24, delivered: 26 },
            { name: "TAC CARRO CGB DANIEL JONATHAN SANABRIA DA SILVA", pending: 86, delivered: 26 },
            { name: "MEI CARRO CGB VILMAR MENDES DA SILVA", pending: 145, delivered: 19 },
            { name: "TAC CARRO CGB003 DANIEL SIQUEIRA", pending: 1, delivered: 0 },
            { name: "CGB 04-MT", pending: 731, delivered: 51 },
            { name: "MEI CARRO CGB LEONY DA SILVA", pending: 60, delivered: 30 },
            { name: "TAC CARRO CGB ROBERTO RIVELINO PIRES MODESTO", pending: 41, delivered: 14 },
            { name: "TAC CARRO CGB WELYTON BATISTA CAMPOS", pending: 107, delivered: 6 },
            { name: "TAC CARRO CGB ALEXSANDRO CAMPOS DE MORAES", pending: 148, delivered: 1 },
            { name: "TAC CARRO CGB MARCIO JAIR DE MORAES", pending: 16, delivered: 0 },
            { name: "TAC CARRO CGB MARIELLY NUNES SIQUEIRA", pending: 45, delivered: 0 },
            { name: "TAC CARRO CGB VANYELLE DE AZEVEDO LEITE", pending: 20, delivered: 0 },
            { name: "TAC CARRO CGB ELAINE ALENCAR SILVA CALISTO", pending: 65, delivered: 0 },
            { name: "TAC MOTO CGB YESMER DE JESUS BRACA RUIZ", pending: 7, delivered: 0 },
            { name: "TAC CARRO CGB FLORISMAR ALVES DE AGUIAR JUNIOR", pending: 55, delivered: 0 },
            { name: "MEI CARRO CGB JOSE SOTERO DA COSTA JUNIOR", pending: 77, delivered: 0 },
            { name: "TAC CARRO CGB JESUS TONY DE ALENCAR CALISTO", pending: 90, delivered: 0 },
            { name: "CGB 05-MT", pending: 531, delivered: 92 },
            { name: "TAC CARRO CGB  JOSE CARLOS DA SILVA", pending: 87, delivered: 69 },
            { name: "TAC CARRO CGB LUCAS SANTOS SILVA", pending: 53, delivered: 15 },
            { name: "TAC CARRO CGB DIELITTON WESLEN NASCIMENTO SPINELLI", pending: 28, delivered: 8 },
            { name: "TAC CARRO CGB EDISON DA GUIA MEIRA", pending: 50, delivered: 0 },
            { name: "MEI CARRO CGB FELIPE FAGNER SIQUEIRA COSTA", pending: 42, delivered: 0 },
            { name: "MEI CARRO CGB FABIO SOUZA", pending: 141, delivered: 0 },
            { name: "TAC CARRO CGB EURICO CESAR SANTOS CARDOSO", pending: 39, delivered: 0 },
            { name: "TAC CARRO CGB JOSE ROBERTO PINTO DA SILVA", pending: 71, delivered: 0 },
            { name: "MEI CARRO CGB DANIEL FELICIANO DO NASCIMENTO FILHO", pending: 1, delivered: 0 },
            { name: "TAC CARRO CGB ALLYSON FIGUEIREDO MARIANO", pending: 12, delivered: 0 },
            { name: "TAC CARRO CGB ANDERSON BARONIO", pending: 7, delivered: 0 },
            { name: "CGR 02-MS", pending: 772, delivered: 118 },
            { name: "CARRO TAC ANDRESSA ALVES DE OLIVEIRA", pending: 35, delivered: 51 },
            { name: "MEI CARRO CGR 002 OVIDIO SALVADOR PASSARELI", pending: 84, delivered: 26 },
            { name: "TAC CARRO CGR 002 HASER SANTOS QUIRINO", pending: 62, delivered: 23 },
            { name: "TAC CARRO CD CGR ARQUILEY MARTINEZ DE OLIVEIRA", pending: 93, delivered: 9 },
            { name: "TAC CARRO CD CGR 002 SIDNEY ZANELLA CABRERA", pending: 75, delivered: 4 },
            { name: "TAC CARRO CGR 002 GEAN PEREIRA VIEIRA", pending: 109, delivered: 4 },
            { name: "TAC CARRO CGR 002 JEZREEL LESCANO OLIVEIRA", pending: 8, delivered: 1 },
            { name: "TAC CARRO CGR 02 PRISCILLA DA SILVA JARA", pending: 74, delivered: 0 },
            { name: "TAC CARRO CGR 002 VITOR BATISTA ROCHA", pending: 232, delivered: 0 },
            { name: "CGR 03-MS", pending: 451, delivered: 139 },
            { name: "TAC CARRO CGR 003 VANDER COSTA PEREIRA", pending: 38, delivered: 46 },
            { name: "MEI CARRO CGR MESAQUE REIS DOS SANTOS", pending: 55, delivered: 45 },
            { name: "TAC CARRO CGR 003 ARTUR JORGE MAECAWA", pending: 44, delivered: 30 },
            { name: "TAC CARRO CGR 003 CARLOS EDUARDO PAES", pending: 34, delivered: 17 },
            { name: "TAC CARRO CGR 003 ADEMIRO FERREIRA LOPES", pending: 83, delivered: 1 },
            { name: "MEI CARRO CGR JOSELY IBANES VICENTE", pending: 81, delivered: 0 },
            { name: "MEI CARRO CGR WILLIAM GONÇALVES PRECINATO", pending: 114, delivered: 0 },
            { name: "TAC CARRO CGR 003 TIAGO DE OLIVEIRA GOMES", pending: 2, delivered: 0 },
            { name: "CGR 04-MS", pending: 385, delivered: 121 },
            { name: "TAC CARRO CGR 04 ALEX ZANARIO DA SILVA DOS REIS", pending: 6, delivered: 35 },
            { name: "TAC CARRO CGR 004 PAULO ROBERTO ESCOBAR DOS SANTOS", pending: 73, delivered: 25 },
            { name: "TAC CARRO CGR 04 ELI BORGES DE OLIVEIRA JUNIOR", pending: 36, delivered: 20 },
            { name: "MEI CARRO CGR 004  JEFERSON DE ANDRADE", pending: 36, delivered: 19 },
            { name: "MEI CARRO CGR 004 MARCIANO LOPES RESQUIM JUNIOR", pending: 49, delivered: 19 },
            { name: "TAC MOTO CD CGR 004 ANDRE LUIS ROJAS GIMENES", pending: 92, delivered: 2 },
            { name: "TAC CARRO CGR 004 ANDRE LUIS PEREIRA DA SILVA", pending: 0, delivered: 1 },
            { name: "CD CGR 004 LOGIN BAIXA", pending: 1, delivered: 0 },
            { name: "MEI CARRO CGR 04 EDENILSON ESPINDOLA DE CASTRO", pending: 2, delivered: 0 },
            { name: "TAC CARRO CGR 004 LEANDRO CAIQUE MENEZES DA SILVA", pending: 90, delivered: 0 },
            { name: "CGR 05-MS", pending: 601, delivered: 284 },
            { name: "TAC CARRO CGR 005 MARIA HELENA DA SILVA MATIAS", pending: 20, delivered: 89 },
            { name: "MEI CARRO CGR DIEGO CORREIA BARBOSA", pending: 59, delivered: 47 },
            { name: "TAC CARRO CGR VALDECIR ALVES DE CASTRO", pending: 102, delivered: 44 },
            { name: "MEI CGR 05 MS CARRO THIAGO OLIVEIRA DA VEIGA", pending: 56, delivered: 31 },
            { name: "TAC CARRO CGR 005 ALEXANDRE HOKAMA DUTRA", pending: 128, delivered: 28 },
            { name: "MEI CARRO CGR 05 MS ANANIAS SOARES DE OLIVEIRA", pending: 70, delivered: 27 },
            { name: "MEI CARRO CGR 005 MATHEUS CORDEIRO VILANOVA", pending: 95, delivered: 18 },
            { name: "MEI CARRO CGR 05 MS BRUNO DA SILVA DE ALMEIDA", pending: 68, delivered: 0 },
            { name: "LOGIN DE BAIXA CGR 005", pending: 3, delivered: 0 },
            { name: "CGR -MS", pending: 709, delivered: 119 },
            { name: "TAC CARRO CGR 001 KAUAN JUNIOR SILVA PAIVA", pending: 73, delivered: 41 },
            { name: "MEI CARRO CGR KEDSON FERREIRA DE AGUIAR", pending: 97, delivered: 28 },
            { name: "TAC CARRO CGR JENIFER CAROLINE DA SILVA CARISSIMO", pending: 75, delivered: 23 },
            { name: "TAC CARRO CGR 001 GEOVANA MARTINE ROCHA", pending: 116, delivered: 19 },
            { name: "TAC CARRO CGR THAINARA BOBADILHA DA MATA SOARES", pending: 41, delivered: 8 },
            { name: "TAC CARRO CGR 001 DEIVYD PAIVA MALAQUIAS", pending: 41, delivered: 0 },
            { name: "TAC MOTO CGR 001 VAGNER DOS SANTOS LIMA", pending: 186, delivered: 0 },
            { name: "TAC CARRO CD CGR RONNI PETERSON RAMIRES", pending: 9, delivered: 0 },
            { name: "TAC CARRO CGR ANDRE VENANCIO ORUE MEDINA", pending: 71, delivered: 0 },
            { name: "CHS -MS", pending: 30, delivered: 51 },
            { name: "TAC CARRO LUCIANA DE PAULA MENEZES", pending: 21, delivered: 33 },
            { name: "MEI CARRO CHS NEDIMAR DIAS B1", pending: 5, delivered: 17 },
            { name: "TAC CARRO CHS GLAUCIELE DE SOUZA MACHADO", pending: 0, delivered: 1 },
            { name: "TAC CARRO CHS GLEICIANNE GOMES DOS SANTOS", pending: 4, delivered: 0 },
            { name: "CMP-MT", pending: 239, delivered: 92 },
            { name: "AGR CARRO CMP PAULO FERNANDES DA CRUZ", pending: 46, delivered: 37 },
            { name: "MEI CARRO CMP EDUARDO LOPES DAMACENO", pending: 102, delivered: 17 },
            { name: "AGR CARRO CMP ENALIO BATISTA DAMASCENO", pending: 57, delivered: 14 },
            { name: "AGR CARRO CMP CLEIDI APARECIDA DE OLIVEIRA LOPES", pending: 24, delivered: 13 },
            { name: "TAC CARRO - ADILSON FERNANDES DE SOUSA MACHADO", pending: 10, delivered: 11 },
            { name: "CNF -MT", pending: 115, delivered: 98 },
            { name: "TAC MOTO CNF MIZAEL BORGES DA SILVA", pending: 21, delivered: 68 },
            { name: "TAC CARRO CNF JESSICA DALETEZZE DOS REIS", pending: 39, delivered: 26 },
            { name: "TAC CARRO CNF LUCIANO JUSTINO REIS", pending: 36, delivered: 3 },
            { name: "TAC CARRO CNF PEDRO FERREIRA SILVA", pending: 7, delivered: 1 },
            { name: "TAC CARRO CNF CARLOS MAGNO PINTO", pending: 11, delivered: 0 },
            { name: "TAC CARRO CNF THIAGO PEREIRA COSTA", pending: 1, delivered: 0 },
            { name: "CRB -MS", pending: 195, delivered: 9 },
            { name: "TAC CARRO CRB Jeniffer Cori Aragon", pending: 21, delivered: 6 },
            { name: "TAC CARRO CRB Adenilson felix", pending: 2, delivered: 2 },
            { name: "TAC MOTO CRB SILVIA LUCIANA FORTES", pending: 1, delivered: 1 },
            { name: "MEI CARRO CGR PAULO MERCEDES ROCHA", pending: 171, delivered: 0 }
        ]
    },
    "CTL -GO": {
        totalPending: 5,
        totalDelivered: 2,
        totalOverall: 7,
        drivers: [
            { name: "TAC CARRO - WANDERLEY JACOB RODRIGUES", pending: 0, delivered: 1 },
            { name: "TAC CARRO - CRISTIAN SILVEIRA CAMPOS", pending: 3, delivered: 1 },
            { name: "MEI CARRO - JESSICA MENDES ARAUJO", pending: 2, delivered: 0 }
        ]
    },
    "CTN -GO": {
        totalPending: 136,
        totalDelivered: 15,
        totalOverall: 151,
        drivers: [
            { name: "TAC CARRO - DIRCEU ALVES DE SANTANA JUNIOR", pending: 136, delivered: 14 },
            { name: "MEI CARRO - JANAINA DOS SANTOS DE MORAIS PEREIRA", pending: 0, delivered: 1 },
            { name: "CXM -MS", pending: 1, delivered: 0 },
            { name: "TAC CARRO JESSICA SILVA DE CARVALHO", pending: 1, delivered: 0 },
            { name: "CZS -AC", pending: 3, delivered: 0 },
            { name: "TAC MOTO RAELITON  DE SOUZA SILVA", pending: 1, delivered: 0 },
            { name: "TAC MOTO - EMANUEL DA SILVA SANTOS", pending: 2, delivered: 0 },
            { name: "DOU -MS", pending: 0, delivered: 4 },
            { name: "TAC MOTO DOU LEILA VIEIRA DA SILVA", pending: 0, delivered: 3 },
            { name: "TAC CARRO DOU FERNANDA LOBO VIEIRADA SILVA", pending: 0, delivered: 1 },
            { name: "EMA -DF", pending: 167, delivered: 97 },
            { name: "MEI CARRO - JONATA SILVA CUTRIM", pending: 37, delivered: 39 },
            { name: "MEI CARRO - MARIA JOSE DA ROCHA", pending: 23, delivered: 27 },
            { name: "MEI CARRO - MAXWELL GOMES DE JESUS", pending: 61, delivered: 22 },
            { name: "MEI CARRO - ANA CLAUDIA DE SA GUIMARAES", pending: 20, delivered: 9 },
            { name: "TAC CARRO - INALDO SOARES SILVA FILHO", pending: 26, delivered: 0 },
            { name: "F AGL-GO", pending: 504, delivered: 120 },
            { name: "TAC MOTO - RODRIGO ALVES LEITE", pending: 3, delivered: 33 },
            { name: "MEI CARRO - WALLACE ARAUJO TEODORO", pending: 44, delivered: 24 },
            { name: "MEI CARRO - DANILO SOUSA DA SILVA", pending: 30, delivered: 22 },
            { name: "TAC CARRO - JHONATA NOBREGA DINIZ", pending: 46, delivered: 20 },
            { name: "TAC CARRO - ANDERSON DE JESUS", pending: 52, delivered: 16 },
            { name: "TAC CARRO - JORGE NASCIMENTO PEREIRA JUNIOR", pending: 25, delivered: 3 },
            { name: "ETC CARRO F AGL - MATEUS WILLIAM DE SOUSA SALES", pending: 55, delivered: 2 },
            { name: "F AGL - RONIEL DE PAULA MARES", pending: 43, delivered: 0 },
            { name: "ETC CARRO F AGL - VALERIANO DO REIS SOARES", pending: 116, delivered: 0 },
            { name: "MEI CARRO - FERNANDA SOUZA BARROS", pending: 90, delivered: 0 },
            { name: "F FMA-GO", pending: 333, delivered: 60 },
            { name: "MEI CARRO - ZELI RIBEIRO GUIMARAES", pending: 40, delivered: 32 },
            { name: "MEI CARRO - GENIR TEIXEIRA BARBOSA", pending: 6, delivered: 17 },
            { name: "ETC MOTO FMA - JOAO VICTOR RODRIGUES DOS SANTOS", pending: 38, delivered: 10 },
            { name: "TAC CARRO - JOILSON PEREIRA DOS SANTOS", pending: 61, delivered: 1 },
            { name: "ETC MOTO F FMA - ELIELTON ALVARES DE SOUSA", pending: 10, delivered: 0 },
            { name: "ETC CARRO F FMA - DAIANNE FERNANDES DA SILVA", pending: 178, delivered: 0 },
            { name: "FMA -GO", pending: 1, delivered: 0 },
            { name: "TAC CARRO - LUIS DANILO SANTOS CARVALHO", pending: 1, delivered: 0 },
            { name: "GAM -DF", pending: 120, delivered: 122 },
            { name: "TAC CARRO - KLEBER SILVA DE ALMEIDA", pending: 68, delivered: 59 },
            { name: "TAC CARRO - JORGE HENRIQUE NAZARIO C DE FREITAS", pending: 0, delivered: 42 },
            { name: "TAC CARRO - LEONARDO DA CUNHA SILVA", pending: 52, delivered: 21 }
        ]
    },
    "PON -GO": {
        totalPending: 143,
        totalDelivered: 0,
        totalOverall: 143,
        drivers: [
            { name: "MEI CARRO - GUILHERME MORAIS COSTA", pending: 95, delivered: 0 },
            { name: "MEI CARRO - ALEKSANDER KAMENAK DIAS DE MELO", pending: 48, delivered: 0 },
            { name: "POS -GO", pending: 3, delivered: 0 },
            { name: "TAC CARRO - SIRLEI ALVES DOS SANTOS", pending: 2, delivered: 0 },
            { name: "TAC CARRO - GABRIEL GUIMARAES LUCENA", pending: 1, delivered: 0 }
        ]
    },
    "TRD -GO": {
        totalPending: 257,
        totalDelivered: 59,
        totalOverall: 316,
        drivers: [
            { name: "TAC CARRO - RENATO GONCALVES BUENO", pending: 51, delivered: 33 },
            { name: "MEI CARRO - SAMUEL NEVES DE MELO SILVA", pending: 20, delivered: 19 },
            { name: "MEI CARRO - DAVI BARBOSA NOBRE", pending: 38, delivered: 5 },
            { name: "TAC CARRO - JEAN JEFERSON SOARES FERREIRA", pending: 0, delivered: 1 },
            { name: "MEI CARRO - SIMONE ALVES DE SOUZA", pending: 54, delivered: 1 },
            { name: "TAC CARRO - JULIANO FERREIRA PIRES", pending: 91, delivered: 0 },
            { name: "TAC CARRO - CLEOMAR NONATO DA LUZ", pending: 3, delivered: 0 }
        ]
    },
    "GYN 02-GO": {
        totalPending: 527,
        totalDelivered: 107,
        totalOverall: 634,
        drivers: [
            { name: "TAC CARRO - AURELIANO EURIPEDES DE PAULA TRINDADE", pending: 113, delivered: 52 },
            { name: "TAC CARRO - VINICIUS VIGNER DE ALMEIDA", pending: 78, delivered: 37 },
            { name: "TAC CARRO - LUCAS MATOS DA SILVA", pending: 120, delivered: 18 },
            { name: "MEI CARRO - WISLEY ALVES DA SILVA", pending: 123, delivered: 0 },
            { name: "MEI CARRO - CLAUDIO MOREIRA CARVALHO", pending: 2, delivered: 0 },
            { name: "TAC CARRO - SARA CRISTINE RIBEIRO DOS SANTOS", pending: 91, delivered: 0 }
        ]
    },
    "GYN 03-GO": {
        totalPending: 1245,
        totalDelivered: 411,
        totalOverall: 1656,
        drivers: [
            { name: "TAC CARRO -  WYVES RIOS MORAES", pending: 58, delivered: 63 },
            { name: "TAC CARRO - LUCAS FERREIRA ALVES MENDONCA", pending: 0, delivered: 53 },
            { name: "TAC CARRO - VINICIUS MAIONE SILVA CRUZ", pending: 73, delivered: 46 },
            { name: "TAC CARRO - JEZIEL FIGUEIRA GOMES", pending: 55, delivered: 45 },
            { name: "MEI CARRO - RENATO REZENDE DE BARROS", pending: 106, delivered: 41 },
            { name: "MEI CARRO - LEANDRO MANOEL DA SILVA", pending: 98, delivered: 35 },
            { name: "MEI CARRO - FABRICIO ALVES PACHECO", pending: 68, delivered: 29 },
            { name: "TAC CARRO - UEDSON MARQUES MOITINHO", pending: 78, delivered: 25 },
            { name: "TAC CARRO - EDSON LUIS DE OLIVEIRA", pending: 74, delivered: 25 },
            { name: "TAC CARRO - STEFANNY BORGES DOS SANTOS", pending: 88, delivered: 19 },
            { name: "TAC CARRO - LAIS MACHADO DOS SANTOS SOUZA", pending: 0, delivered: 16 },
            { name: "TAC CARRO - WALDEMIR SANTANA DA COSTA", pending: 26, delivered: 14 },
            { name: "MEI CARRO - MATEUS PEREIRA CAETANO", pending: 40, delivered: 0 },
            { name: "TAC CARRO - HUGO FERREIRA FARIA", pending: 31, delivered: 0 },
            { name: "MEI CARRO - DIEGO LIMA REGO", pending: 66, delivered: 0 },
            { name: "MEI CARRO - THIAGO ROSA VITURINO", pending: 162, delivered: 0 },
            { name: "TAC CARRO - GIOVANNI HENRIQUE ALVES ALVIM", pending: 42, delivered: 0 },
            { name: "MEI CARRO - WESLEY DIVINO FRANCO", pending: 180, delivered: 0 }
        ]
    },
    "GYN 04-GO": {
        totalPending: 419,
        totalDelivered: 123,
        totalOverall: 542,
        drivers: [
            { name: "TAC CARRO - GLEYBE RENATO ANDRADE", pending: 143, delivered: 68 },
            { name: "TAC CARRO - CARLOS HELIABY NEVES VIEIRA", pending: 109, delivered: 55 },
            { name: "TAC CARRO - JORDANA MENDES DE SOUSA", pending: 1, delivered: 0 },
            { name: "TAC CARRO - SEGINALDO ANTONIO DA SILVA", pending: 1, delivered: 0 },
            { name: "MEI CARRO - PEDRO HENRIQUE PORFIRIO DE OLIVEIRA", pending: 165, delivered: 0 }
        ]
    },
    "GYN 05-GO": {
        totalPending: 367,
        totalDelivered: 124,
        totalOverall: 491,
        drivers: [
            { name: "TAC CARRO - DEUSDETE FERREIRA DA ROCHA", pending: 187, delivered: 69 },
            { name: "TAC CARRO - MARCIONILIO MOREIRA BARBOSA", pending: 159, delivered: 46 },
            { name: "TAC CARRO - LEORGINA MARIA DUTRA SILVA JACINTO", pending: 21, delivered: 9 }
        ]
    },
    "GYN 06-GO": {
        totalPending: 820,
        totalDelivered: 148,
        totalOverall: 968,
        drivers: [
            { name: "TAC CARRO - WAGNER DIAS JUNIOR", pending: 148, delivered: 55 },
            { name: "TAC CARRO - AMANCIO MARIANO FIRMINO FILHO", pending: 47, delivered: 54 },
            { name: "MEI CARRO - JULIENE DAYSE VASCONCELOS DA COSTA", pending: 110, delivered: 19 },
            { name: "TAC CARRO - PRISCILA GENOVESI BOCCHI", pending: 115, delivered: 17 },
            { name: "MEI CARRO - WANDERSON BARROS DA SILVA", pending: 139, delivered: 2 },
            { name: "MEI CARRO - LUIZ FELIPE DE ABREU ROCHA", pending: 161, delivered: 1 },
            { name: "MEI CARRO - LEONILDA DA SILVA BRAGA CORDOVIL", pending: 100, delivered: 0 }
        ]
    },
    "GYN 07-GO": {
        totalPending: 526,
        totalDelivered: 137,
        totalOverall: 663,
        drivers: [
            { name: "TAC CARRO - SIRLEY CASTILHO CABRAL DA CRUZ", pending: 1, delivered: 39 },
            { name: "TAC CARRO - WASHINGTON FERREIRA", pending: 83, delivered: 35 },
            { name: "TAC CARRO - PAULO HENRIQUE FERNANDES DA SILVA", pending: 18, delivered: 29 },
            { name: "MEI CARRO - GEOVANE DOS SANTOS OLIVEIRA", pending: 25, delivered: 27 },
            { name: "TAC CARRO - WELLINGTON RIBEIRO DE LIMA", pending: 83, delivered: 6 },
            { name: "MEI CARRO - WELLIKY MOREIRA DE CARVALHO", pending: 74, delivered: 1 },
            { name: "TAC CARRO - ANNE CAROLINY ALVES DOS REIS", pending: 74, delivered: 0 },
            { name: "MEI CARRO - MARCOS JUNIO BUENO DE OLIVEIRA", pending: 107, delivered: 0 },
            { name: "TAC CARRO - SILOMI MATIAS PEREIRA", pending: 22, delivered: 0 },
            { name: "TAC CARRO - JOSUE PEDRO ALVES GOMES", pending: 39, delivered: 0 },
            { name: "JPN -RO", pending: 22, delivered: 0 },
            { name: "TAC CARRO STANLEY EDUARDO REGO SILVA MAIO", pending: 1, delivered: 0 },
            { name: "TAC CARRO LUCIVANE MARIA DE SOUZA", pending: 1, delivered: 0 },
            { name: "TAC MOTO CLAUDIO OLIVEIRA PACATONI", pending: 16, delivered: 0 },
            { name: "TAC CARRO SABLINE FREITAS MARCOLINO", pending: 3, delivered: 0 },
            { name: "TAC CARRO SANDOVALDO DOS SANTOS FILHO", pending: 1, delivered: 0 },
            { name: "JRD -MS", pending: 636, delivered: 0 },
            { name: "TAC - CARRO DIJANIR HORTÊNCIO", pending: 175, delivered: 0 },
            { name: "TAC-CARRO - EDGAR DUTRA DA LUZ", pending: 73, delivered: 0 },
            { name: "TAC CARRO JRD JAMIL PEDRO FILHO", pending: 5, delivered: 0 },
            { name: "MEI - CARRO VINICIUS GAVILAN LEDESMA CHAVES", pending: 2, delivered: 0 },
            { name: "ETC CARRO - RONALDO MENDONCA DOS SANTOS", pending: 280, delivered: 0 },
            { name: "TAC - CARRO - FILIPE SILVA BENNETT", pending: 101, delivered: 0 }
        ]
    },
    "ITR -GO": {
        totalPending: 0,
        totalDelivered: 0,
        totalOverall: 0,
        drivers: [
        ]
    },
    "JTI -GO": {
        totalPending: 19,
        totalDelivered: 1,
        totalOverall: 20,
        drivers: [
            { name: "TAC CARRO - VALDIVINO CARLOS DE MORAIS", pending: 0, delivered: 1 },
            { name: "MEI CARRO - GUILHERME RODRIGUES ROCHA FARIAS", pending: 2, delivered: 0 },
            { name: "TAC CARRO - HELLEN OLIVEIRA DE AZARIAS", pending: 17, delivered: 0 },
            { name: "JUI -MT", pending: 77, delivered: 33 },
            { name: "MEI CARRO JUI ELIO LOURENCO DE OLIVEIRA", pending: 54, delivered: 25 },
            { name: "MEI CARRO JUI KELLY DA NOBREGA GOMES", pending: 14, delivered: 7 },
            { name: "MEI CARRO JUI LAUDICEIA DOS SANTOS DE SA IGNACIO", pending: 9, delivered: 1 },
            { name: "LRV -MT", pending: 27, delivered: 11 },
            { name: "TAC CARRO -  VICTOR SILVA DOS SANTOS", pending: 0, delivered: 9 },
            { name: "TAC CARRO LRV MATHEUS BEZERRA DA SILVA CASOLL", pending: 5, delivered: 1 },
            { name: "TAC CARRO LRV LEONARDO MONTEIRO DO NASCIMENTO", pending: 0, delivered: 1 },
            { name: "TAC CARRO LRV ALESSON CESAR DOS SANTOS", pending: 1, delivered: 0 },
            { name: "TAC CARRO LRV MAYCON CLAYTON SILVA SOARES", pending: 6, delivered: 0 },
            { name: "TAC CARRO LRV GABRIEL DA SILVA CARVALHO", pending: 7, delivered: 0 },
            { name: "TAC CARRO LRV KEYSTON RODRIGUES PEREIRA", pending: 8, delivered: 0 },
            { name: "LUZ -GO", pending: 115, delivered: 138 },
            { name: "TAC CARRO - LEILA JULLIANA AFONSO DE ABREU", pending: 3, delivered: 60 },
            { name: "TAC CARRO - DAIANA LEMOS DOS SANTOS", pending: 33, delivered: 50 },
            { name: "TAC CARRO - ERICK ALYSSON RABELO", pending: 12, delivered: 28 },
            { name: "TAC CARRO - MATEUS SANTOS GOMES", pending: 67, delivered: 0 },
            { name: "MDT -MT", pending: 14, delivered: 17 },
            { name: "TAC CARRO - RONIVON RAMOS DA SILVA FEITOSA", pending: 8, delivered: 17 },
            { name: "TAC CARRO MDT LUANA ALVES NASCIMENTO", pending: 6, delivered: 0 },
            { name: "NDI -MS", pending: 120, delivered: 0 },
            { name: "MEI CARRO DOU EVANDRO JOSE SIQUEIRA", pending: 1, delivered: 0 },
            { name: "TAC CARRO NDI VALDECIR MARTINS VAIS", pending: 28, delivered: 0 },
            { name: "TAC CARRO NDI HELIENE MAGALHOES DE MIRANDA SANTOS", pending: 91, delivered: 0 },
            { name: "NVT -MT", pending: 815, delivered: 8 },
            { name: "TAC CARRO NVT GEAZI HENRIQUE MOREIRA PEREIRA", pending: 74, delivered: 6 },
            { name: "TAC CARRO NVT MICHELE GONÇALVES DE SANTANA", pending: 78, delivered: 2 },
            { name: "TAC CARRO NVT JOAO PAULO MENDONÇA AZEVEDO", pending: 144, delivered: 0 },
            { name: "TAC MOTO NVT ANGELICA CRISTINA DO NASCIMENTO", pending: 60, delivered: 0 },
            { name: "TAC CARRO NVT DIONATA DA COSTA VINHOTE", pending: 66, delivered: 0 },
            { name: "TAC CARRO NVT LETICIA LAMPERT", pending: 131, delivered: 0 },
            { name: "TAC CARRO NVT EBER DA COSTA AMARAL", pending: 101, delivered: 0 },
            { name: "TAC CARRO NVT DIOGNES DA SILVA TASSOTTI", pending: 84, delivered: 0 },
            { name: "MEI CARRO NVT SAMUEL RIBEIRO JUNIOR", pending: 77, delivered: 0 },
            { name: "OCD-GO", pending: 276, delivered: 60 },
            { name: "MEI CARRO - MARCIA MARIA LINDOMAR", pending: 37, delivered: 23 },
            { name: "MEI CARRO - WASHINGTON FIRMINO DA COSTA", pending: 29, delivered: 19 },
            { name: "TAC CARRO - DANILO ROMULO GOMES GONCALVES", pending: 48, delivered: 18 },
            { name: "TAC CARRO - ISAQUE SOARES VITORIO", pending: 45, delivered: 0 },
            { name: "MEI CARRO - JOSE WILLIAN DE JESUS SILVA", pending: 24, delivered: 0 },
            { name: "MEI CARRO - KATIANA MESSIAS LOPES CAMELO", pending: 93, delivered: 0 },
            { name: "PLDF -DF", pending: 165, delivered: 84 },
            { name: "TAC CARRO - ANDRE DOS SANTOS COSTA", pending: 18, delivered: 51 },
            { name: "MEI CARRO - RAFAEL ALVES DA SILVA", pending: 43, delivered: 18 },
            { name: "MEI CARRO - NEURIANE MENDES COSTA", pending: 36, delivered: 14 },
            { name: "TAC CARRO - GLEYCI FERREIRA COELHO", pending: 64, delivered: 1 },
            { name: "TAC CARRO - AMANDA BEZERRA DOS OLIVEIRA", pending: 4, delivered: 0 },
            { name: "PLN -GO", pending: 3, delivered: 0 },
            { name: "MEI CARRO - ESTENIO GOMES AFFONSO", pending: 3, delivered: 0 },
            { name: "PNT-MS", pending: 3, delivered: 1 },
            { name: "TAC MOTO PNT JEAN CARLOS JACQUES", pending: 0, delivered: 1 },
            { name: "TAC CARRO PNT JONATAN PAIM RIVAS", pending: 1, delivered: 0 },
            { name: "TAC CARRO PNT THIAGO HENRIQUE VERÃO JARA", pending: 2, delivered: 0 }
        ]
    },
    "QUI -GO": {
        totalPending: 1,
        totalDelivered: 0,
        totalOverall: 1,
        drivers: [
            { name: "TAC CARRO - WESLEY LIMA REZENDE", pending: 1, delivered: 0 },
            { name: "RBR 02-AC", pending: 0, delivered: 1 },
            { name: "TAC CARRO MARIANA MARCELE DOS REIS FRANCA", pending: 0, delivered: 1 },
            { name: "RBR -AC", pending: 48, delivered: 0 },
            { name: "TAC CARRO SEBASTIANA QUEIROZ DA SILVA", pending: 3, delivered: 0 },
            { name: "TAC CARRO REINALDO FERREIRA LIMA", pending: 1, delivered: 0 },
            { name: "TAC CARRO ANDERSON DE SOUZA BARBOSA", pending: 43, delivered: 0 },
            { name: "TAC CARRO LEONARDO DA SILVA NASCIMENTO", pending: 1, delivered: 0 },
            { name: "RDM -RO", pending: 1174, delivered: 73 },
            { name: "TAC CARRO RAFAEL GOMES DE ARAUJO", pending: 185, delivered: 34 },
            { name: "TAC CARRO MATEUS SOARES PROCHNOW", pending: 268, delivered: 15 },
            { name: "TAC CARRO SAMARA CRISTINA PAULI", pending: 19, delivered: 14 },
            { name: "TAC CARRO SANDRA LUCIMAR RODRIGUES", pending: 32, delivered: 5 },
            { name: "MEI CARRO EDER ANTONIO ELLY", pending: 188, delivered: 3 },
            { name: "TAC CARRO PAULO HENRIQUE BOONE DA SILVA", pending: 123, delivered: 2 },
            { name: "TAC CARRO DOUGLAS SIQUEIRA FIRMINO", pending: 190, delivered: 0 },
            { name: "TAC CARRO GILMAR RODRIGUES DA SILVA", pending: 1, delivered: 0 },
            { name: "TAC CARRO DAIANE GHILARDI", pending: 135, delivered: 0 },
            { name: "TAC CARRO RENATA KATHIELI GRACIOLLI", pending: 33, delivered: 0 },
            { name: "RFI -DF", pending: 364, delivered: 47 },
            { name: "TAC CARRO - DANIEL ROBERTO DOS SANTOS NEVES", pending: 52, delivered: 32 },
            { name: "TAC CARRO - RAFAELA SILVA BRITO DAS CHAGAS", pending: 46, delivered: 14 },
            { name: "TAC CARRO - MARTA HELENA CASTRO DE SOUZA", pending: 92, delivered: 1 },
            { name: "TAC CARRO - FRANCISCO ANTONIO PEREIRA DA SILVA", pending: 88, delivered: 0 },
            { name: "TAC CARRO - HEULER BEZERRA DE OLIVEIRA", pending: 86, delivered: 0 },
            { name: "ROO -MT", pending: 1515, delivered: 179 },
            { name: "TAC CARRO ROO ISCK ENIO DOS SANTOS", pending: 64, delivered: 56 },
            { name: "MEI CARRO ROO ADMILSON PEREIRA BARBOSA", pending: 170, delivered: 37 },
            { name: "MEI CARRO ROO DANIEL DE JESUS SOUZA", pending: 19, delivered: 33 },
            { name: "MEI CARRO ROO WAGNER FERNANDO DA SILVA MAGALHAES", pending: 121, delivered: 27 },
            { name: "MEI CARRO ROO CLAUDEIR RODRIGUES", pending: 187, delivered: 16 },
            { name: "AGR CARRO ROO JEFTE CHARLLES PAES", pending: 34, delivered: 7 },
            { name: "AGR CARRO ROO THEYDH AYNNE DORNE", pending: 0, delivered: 2 },
            { name: "MEI CARRO ROO RODRIGO MARCEL BARBOSA DOS SANTOS", pending: 29, delivered: 1 },
            { name: "MEI CARRO ROO FERNANDO AUGUSTO DA SILVA MAGALHAES", pending: 114, delivered: 0 },
            { name: "AGR CARRO ROO WATILLA HENRIQUE GONÇALVES", pending: 156, delivered: 0 },
            { name: "AGR CARRO ROO AILSON PEREIRA BARBOSA", pending: 143, delivered: 0 },
            { name: "MEI CARRO ROO FERNANDO DE ALMEIDA DOURADO", pending: 8, delivered: 0 },
            { name: "AGR CARRO ROO GUSTAVO SALVIAN", pending: 117, delivered: 0 },
            { name: "MEI CARRO ROO TIAGO GILSON ALVES DA SILVA", pending: 159, delivered: 0 },
            { name: "AGR CARRO ROO MARK OURO BRANCO", pending: 42, delivered: 0 },
            { name: "MEI CARRO GGA LAISON BRUNO", pending: 1, delivered: 0 },
            { name: "MEI CARRO FLAVIA PEDRA PRETA", pending: 25, delivered: 0 },
            { name: "MEI CARRO ROO ATILA OLIVEIRA COELHO", pending: 126, delivered: 0 }
        ]
    },
    "RVD -GO": {
        totalPending: 68,
        totalDelivered: 16,
        totalOverall: 84,
        drivers: [
            { name: "TAC CARRO - FLAUBER STEFANIO MORENO", pending: 4, delivered: 14 },
            { name: "TAC CARRO - SAMARA KELLIS PEREIRA DOS SANTOS", pending: 2, delivered: 1 },
            { name: "MEI CARRO - VIVIANA DIAS DA COSTA", pending: 62, delivered: 1 },
            { name: "SAMS -DF", pending: 151, delivered: 137 },
            { name: "TAC CARRO - PABLO VIEIRA MOREIRA", pending: 1, delivered: 49 },
            { name: "TAC CARRO - MARYNEIDE DE ALBUQUERQUE FERNANDES", pending: 27, delivered: 24 },
            { name: "TAC CARRO - LUIZA SOARES DE OLIVEIRA", pending: 55, delivered: 21 },
            { name: "TAC CARRO - EDMILSON DIAS DE OLIVEIRA", pending: 58, delivered: 20 },
            { name: "TAC MOTO - ROGERIO FERNANDES DOS ANJOS", pending: 0, delivered: 9 },
            { name: "TAC MOTO - VINICIUS LISBOA NUNES", pending: 0, delivered: 8 },
            { name: "TAC MOTO - AGNES CARDOSO CIRQUEIRA", pending: 0, delivered: 6 },
            { name: "TAC MOTO - DJAKES LIMA DE OLIVEIRA", pending: 10, delivered: 0 },
            { name: "SBN -DF", pending: 441, delivered: 138 },
            { name: "TAC CARRO - DANIELE SILVA COSTA", pending: 47, delivered: 42 },
            { name: "TAC CARRO - PAULO ROGERIO DOS SANTOS GAMA", pending: 85, delivered: 34 },
            { name: "TAC CARRO - LEONARDO OLIVEIRA ATHAYDE", pending: 49, delivered: 25 },
            { name: "MEI CARRO - VITORIA KAROLINY MOREIRA SANTINO", pending: 14, delivered: 16 },
            { name: "TAC CARRO - VITOR MOREIRA SANTINO", pending: 66, delivered: 9 },
            { name: "MEI CARRO - JOSE TALLES ARAUJO BARROS", pending: 77, delivered: 6 },
            { name: "MEI CARRO - ERIBERGSON BEZERRA EMILIANO", pending: 23, delivered: 4 },
            { name: "MEI CARRO - NATHALIA CRISTINA GUIDA DOS SANTOS", pending: 65, delivered: 2 },
            { name: "MEI CARRO - JADSON PINTO DA SILVA", pending: 1, delivered: 0 },
            { name: "TAC CARRO - JORGE BATISTA DE SOUZA", pending: 14, delivered: 0 }
        ]
    },
    "SEN-GO": {
        totalPending: 355,
        totalDelivered: 74,
        totalOverall: 429,
        drivers: [
            { name: "TAC CARRO - FREDERICO DIAS CASTRO", pending: 68, delivered: 25 },
            { name: "TAC CARRO - LUIZ EDUARDO RODRIGUES MARTINS", pending: 46, delivered: 23 },
            { name: "MEI CARRO -  FABIO JUNIO BATISTA", pending: 34, delivered: 20 },
            { name: "TAC CARRO - RICARDO SILVA DE SOUSA", pending: 108, delivered: 6 },
            { name: "TAC CARRO - SAMUEL SILVA SANTOS", pending: 58, delivered: 0 },
            { name: "TAC CARRO - RAFAEL IMPERATRIZ DA SILVA", pending: 41, delivered: 0 },
            { name: "SGO -MS", pending: 450, delivered: 0 },
            { name: "MEI CARRO SGO VINICIUS FIGUEIREDO CAMPOS", pending: 104, delivered: 0 },
            { name: "MEI CARRO SGO - DAVI PAIVA VIANA", pending: 346, delivered: 0 },
            { name: "SJA -GO", pending: 62, delivered: 1 },
            { name: "TAC CARRO - ALESSANDRO PEREIRA DOS ANJOS", pending: 62, delivered: 1 },
            { name: "SMD -AC", pending: 500, delivered: 152 },
            { name: "MEI MOTO ANTONIO MARCIO OLIVEIRA DE MEDEIRO", pending: 96, delivered: 93 },
            { name: "TAC CARRO - RICHARD CORDEIRO DA SILVA", pending: 192, delivered: 37 },
            { name: "MEI CARRO RICARDO CESAR COSTA DA SILVA", pending: 212, delivered: 22 },
            { name: "SNP -MT", pending: 111, delivered: 139 },
            { name: "TAC CARRO SNP ITAMAR LOPES VELOSO", pending: 1, delivered: 42 },
            { name: "TAC CARRO SNP LUCAS GABRIEL DE ALMEIDA", pending: 8, delivered: 28 },
            { name: "TAC CARRO SNP ANTÔNIO MIGUEL CAMARGO", pending: 5, delivered: 23 },
            { name: "MEI CARRO SNP EVAELTON DE AMORIM", pending: 42, delivered: 23 },
            { name: "TAC CARRO SNP IGOR SILVA MARTINS", pending: 0, delivered: 21 },
            { name: "MEI CARRO SNP TATIANE DE OLIVEIRA SANTOS", pending: 0, delivered: 2 },
            { name: "TAC CARRO SNP WELLYTON DA SILVA", pending: 41, delivered: 0 },
            { name: "TAC MOTO SNP ODIRLEI ZAROSSI", pending: 2, delivered: 0 },
            { name: "TAC CARRO SNP THIAGO JOSE DE AZEVEDO", pending: 12, delivered: 0 },
            { name: "SRS -MT", pending: 498, delivered: 64 },
            { name: "TAC CARRO SRS JOSÉ FRANCISCO DA SILVA VERAS", pending: 91, delivered: 41 },
            { name: "TAC CARRO SRS LEANDRO SOUZA BEZERRA", pending: 51, delivered: 15 },
            { name: "TAC CARRO SRS ANTONIO JUCELINO MARQUES CARDOSO", pending: 106, delivered: 8 },
            { name: "TAC CARRO SRS ALESSANDRA FERREIRA TAVARES", pending: 8, delivered: 0 },
            { name: "TAC CARRO SRS JENIFER LARA COSTA CERUTTI", pending: 77, delivered: 0 },
            { name: "TAC CARRO  LUIS MARCOS SILVA CORREA", pending: 129, delivered: 0 },
            { name: "TAC CARRO SRS SAMUEL LOUREÇO DE LIMA", pending: 18, delivered: 0 },
            { name: "TAC CARRO SRS EVANILDO MELO PANTOJA", pending: 7, delivered: 0 },
            { name: "TAC CARRO SRS IVONE TIEPO", pending: 11, delivered: 0 },
            { name: "TGA -MT", pending: 1527, delivered: 6 },
            { name: "TAC CARRO TGA RICHARD TUTIACHI DA SILVA", pending: 89, delivered: 4 },
            { name: "TAC CARRO - TATYNARA CRISTINA SANTOS PUKA", pending: 91, delivered: 1 },
            { name: "TAC CARRO TGA ROBSON SANTOS ROSSI", pending: 63, delivered: 1 },
            { name: "TAC MOTO TGA WEVERTON CLEBER MONTEIRO", pending: 39, delivered: 0 },
            { name: "TAC CARRO TGA FABIO DE SOUZA DIAS", pending: 58, delivered: 0 },
            { name: "TAC CARRO TGA DELISE APARECIDA DE SOUZA CORRERIA", pending: 13, delivered: 0 },
            { name: "TAC CARRO - JOSE NILTON ALMEIDA LIMA", pending: 92, delivered: 0 },
            { name: "TAC CARRO TGA MARIA CINTIA MENDES DE SOUZA", pending: 12, delivered: 0 },
            { name: "TAC CARRO - MATHEUS FERREIRA LEMES", pending: 54, delivered: 0 },
            { name: "TAC CARRO TGA ANDRESSA ROSA DE PIERRI", pending: 59, delivered: 0 },
            { name: "TAC CARRO - STEPHANIE DE OLIVEIRA LEANDRO", pending: 102, delivered: 0 },
            { name: "TAC CARRO TGA DENILSON MATIAS DA SILVA", pending: 29, delivered: 0 },
            { name: "TAC CARRO - DEBORA DE ALMEIDA SOUSA", pending: 71, delivered: 0 },
            { name: "TAC CARRO TGA FRANCISCO CARDOZO SANTANA", pending: 19, delivered: 0 },
            { name: "TAC CARRO - GUSTAVO HENRIQUE DECOL DO NASCIMENTO", pending: 128, delivered: 0 },
            { name: "TAC CARRO - Jorge dos Santos Oliveira", pending: 200, delivered: 0 },
            { name: "TAC CARRO TGA RONALDO JOSE DA SILVA", pending: 57, delivered: 0 },
            { name: "TAC CARRO  TGA CRISLANE MANOELA DA SILVA", pending: 17, delivered: 0 },
            { name: "TAC CARRO TGA WAGNER COSTA  ALVES", pending: 38, delivered: 0 },
            { name: "TAC CARRO TGA ALEXIA LIMA MENDES", pending: 109, delivered: 0 },
            { name: "MEI CARRO TGA LUANA CAROLINA OLIVEIRA CORNIANI", pending: 69, delivered: 0 },
            { name: "TAC CARRO TGA AMANDA MARTINS SILVA", pending: 118, delivered: 0 },
            { name: "TGT -DF", pending: 879, delivered: 269 },
            { name: "MEI CARRO - JOSE UILSON CATARINO DA SILVA", pending: 31, delivered: 70 },
            { name: "MEI CARRO - EDUARDO LOURENCO BARROSO", pending: 52, delivered: 58 },
            { name: "TAC CARRO - NARDEL DOS SANTOS SOUSA", pending: 21, delivered: 55 },
            { name: "MEI CARRO - LUCAS FERREIRA VIDAL", pending: 43, delivered: 49 },
            { name: "MEI CARRO - NADINE SEVERINO GOMES", pending: 249, delivered: 24 },
            { name: "MEI CARRO - CLEBER EUSTAQUIO DE JESUS", pending: 92, delivered: 13 },
            { name: "MEI CARRO - CARLIANNI RONDON BOLIVAR", pending: 141, delivered: 0 },
            { name: "MEI CARRO - SANDRA MARA PEREIRA PINTO", pending: 250, delivered: 0 },
            { name: "TLL -MS", pending: 283, delivered: 0 },
            { name: "TAC MOTO VALQUIRIA FREITAS MACIEL", pending: 66, delivered: 0 },
            { name: "TAC CARRO MARISA SOARES LOPES", pending: 135, delivered: 0 },
            { name: "CARRO TAC MAIKON DA SILVA WOLF", pending: 80, delivered: 0 },
            { name: "MOTO TAC DOUGLAS ANTONIO ALVES RIBEIRO", pending: 2, delivered: 0 }
        ]
    },
    "ANP -GO": {
        totalPending: 1153,
        totalDelivered: 110,
        totalOverall: 1263,
        drivers: [
            { name: "MEI CARRO - MAURICIO ANTONIO MENDONCA JUNIOR", pending: 83, delivered: 32 },
            { name: "MEI CARRO - SAMANTA ROSA SILVA PIRES", pending: 114, delivered: 28 },
            { name: "MEI CARRO - GUSTAVO DORNELAS REGES", pending: 96, delivered: 18 },
            { name: "MEI CARRO  -  ALEX ANTONIO COSTA MOREIRA", pending: 73, delivered: 12 },
            { name: "TAC CARRO - JORGE DANIEL EVANGELISTA BUZAGLO", pending: 74, delivered: 8 },
            { name: "MEI CARRO - CAIO CESAR DA SILVA MENDES", pending: 40, delivered: 8 },
            { name: "TAC CARRO - ROBERTO GOMES LIMA", pending: 76, delivered: 4 },
            { name: "TAC CARRO - JEAN PAULO PONTES DONDE", pending: 125, delivered: 0 },
            { name: "MEI CARRO - BRENO HENRIQUE DA SILVA TEIXEIRA", pending: 21, delivered: 0 },
            { name: "MEI CARRO - JAQUELINE RITIELLE ROCHA SILVA", pending: 81, delivered: 0 },
            { name: "TAC CARRO - SHARLES RODRIGUES DA SILVA", pending: 59, delivered: 0 },
            { name: "TAC CARRO - ADEMIR MANOEL FARIA DE OLIVEIRA", pending: 189, delivered: 0 },
            { name: "MEI CARRO - YHORRANI MACEDO COSTA", pending: 122, delivered: 0 }
        ]
    },
    "GNA -GO": {
        totalPending: 230,
        totalDelivered: 0,
        totalOverall: 230,
        drivers: [
            { name: "TAC CARRO - DAIANE KELLY BRAGA FERREIRA", pending: 1, delivered: 0 },
            { name: "MEI CARRO - ARTHUR FRANCA DE DEUS", pending: 83, delivered: 0 },
            { name: "TAC CARRO - LUIS FERNANDO MARTINEZ CANO", pending: 25, delivered: 0 },
            { name: "MEI CARRO - JOAO AUGUSTO GONCALVES NETO", pending: 78, delivered: 0 },
            { name: "TAC CARRO - ADEMIR DIAS FREIRE JUNIOR", pending: 43, delivered: 0 },
            { name: "GNT -MT", pending: 527, delivered: 125 },
            { name: "MEI CARRO GNT ANDERSON JOSE DIDEA", pending: 47, delivered: 30 },
            { name: "MEI CARRO - DERBAL FRANCISCO DA SILVA", pending: 61, delivered: 30 },
            { name: "MEI CARRO - LUCAS DELRIC BARBOSA DA SILVA", pending: 25, delivered: 25 },
            { name: "MEI CARRO GNT AROLDO BERNADO DE SOUZA FILHO", pending: 30, delivered: 21 },
            { name: "AGR MOTO GNT ERICA DA SILVA MEIRELES", pending: 35, delivered: 15 },
            { name: "MEI CARRO GNT GLEISSON HENRIQUE CABRAL DE SOUZA", pending: 16, delivered: 1 },
            { name: "AGR CARRO GNT ANDRESSA ELLY RODRIGUES", pending: 0, delivered: 1 },
            { name: "AGR MOTO GNT DARLEI BISPO SANTANA", pending: 0, delivered: 1 },
            { name: "AGR MOTO GNT  CRISTHIAN PEDROZO VITORINO", pending: 1, delivered: 1 },
            { name: "AGR CARRO ALEXANDRE JUNIOR RITZKE", pending: 3, delivered: 0 },
            { name: "TAC CARRO GNT RAQUEL OLIVEIRA DA SILVA", pending: 102, delivered: 0 },
            { name: "MEI MOTO - IVONETE DE FATIMA ZANCHETA", pending: 116, delivered: 0 },
            { name: "AGR CARRO GNT LEANDRO DE SOUZA CARDOSO", pending: 4, delivered: 0 },
            { name: "AGR CARRO GNT MATHEUS GLOSS SILVA", pending: 45, delivered: 0 },
            { name: "AGR CARRO GNT DIOGO ROSS", pending: 42, delivered: 0 },
            { name: "GUA -DF", pending: 274, delivered: 222 },
            { name: "MEI CARRO - EMANUEL VICTOR MONTEIRO FONSECA", pending: 65, delivered: 63 },
            { name: "MEI CARRO - NIVALDO BUENO DOS SANTOS", pending: 2, delivered: 55 },
            { name: "MEI CARRO - RAFAEL VILLACHAN DAMASCENO", pending: 30, delivered: 51 },
            { name: "MEI CARRO - LEONARDO GOMES DOS REIS", pending: 8, delivered: 27 },
            { name: "MEI CARRO - JOSE DOMINGOS DOURADO VIANA", pending: 0, delivered: 19 },
            { name: "MEI CARRO - ELIO COTEGIPE MIRANDA SILVA", pending: 48, delivered: 6 },
            { name: "MEI CARRO - GLEISSON FERREIRA DOS SANTOS", pending: 36, delivered: 1 },
            { name: "TAC CARRO - ELTON ANTONIO PACHECO LIMA", pending: 15, delivered: 0 },
            { name: "MEI CARRO - RAIANE LEITE OLIVEIRA", pending: 70, delivered: 0 }
        ]
    },
    "IPR -GO": {
        totalPending: 0,
        totalDelivered: 0,
        totalOverall: 0,
        drivers: [
        ]
    },
    "PRG -GO": {
        totalPending: 191,
        totalDelivered: 0,
        totalOverall: 191,
        drivers: [
            { name: "TAC CARRO - GABRIEL BATISTA DUARTE", pending: 57, delivered: 0 },
            { name: "TAC CARRO - DEBORA KARLA MENEZES DE JESUS", pending: 130, delivered: 0 },
            { name: "MEI CARRO - MATHEUS CAVALCANTE PEREIRA", pending: 3, delivered: 0 },
            { name: "MEI CARRO - WILLYAN RODOVAL DA SILVA", pending: 1, delivered: 0 },
            { name: "PTD -MT", pending: 157, delivered: 42 },
            { name: "TAC CARRO PTD BETANIA COSTA ALECRIM", pending: 19, delivered: 25 },
            { name: "TAC MOTO MDT CALEB ALBAREZ FERNANDES", pending: 1, delivered: 10 },
            { name: "TAC CARRO PTD FATIMA DE OLIVEIRA LEANDRO", pending: 2, delivered: 4 },
            { name: "TAC CARRO VALDO OLIVEIRA KUSTHER", pending: 2, delivered: 1 },
            { name: "TAC CARRO PTD ELIZEU FERREIRA KUSTHER", pending: 2, delivered: 1 },
            { name: "TAC CARRO PTD MARISANDRO MARLON R DE OLIVEIRA", pending: 91, delivered: 1 },
            { name: "TAC CARRO ROBERTO PEREIRA DOS SANTOS", pending: 36, delivered: 0 },
            { name: "TAC CARRO PTD NILTOM DE SOUZA SANTOS", pending: 1, delivered: 0 },
            { name: "TAC CARRO PTD EMANOEL DHANATAS SILVA SANTO", pending: 3, delivered: 0 },
            { name: "PVH -RO", pending: 3276, delivered: 328 },
            { name: "TAC CARRO MAGNO RIBEIRO TOLEDO", pending: 101, delivered: 39 },
            { name: "TAC CARRO FRANCISCO VALMIR DA SILVA", pending: 104, delivered: 38 },
            { name: "TAC CARRO EDNA MARIA BATISTA", pending: 66, delivered: 37 },
            { name: "MEI CARRO ELIELSON PEREIRA MARTINS", pending: 123, delivered: 34 },
            { name: "MEI CARRO MAYKON JONATAN BERMUD", pending: 75, delivered: 28 },
            { name: "MEI CARRO RAIMUNDA DE AZEVEDO ARAUJO", pending: 107, delivered: 27 },
            { name: "TAC CARRO ADLER ALVES DE MELO RODRIGUES", pending: 251, delivered: 23 },
            { name: "MEI CARRO LUCAS PEREIRA SILVA", pending: 28, delivered: 23 },
            { name: "MEI CARRO MARCO ANTONIO DA SILVA ROSA JUNIOR", pending: 42, delivered: 15 },
            { name: "TAC CARRO LUSVANIA BELARMINO NOGUEIRA DE FARIAS", pending: 65, delivered: 14 },
            { name: "TAC CARRO LUANA DANTAS DE BRITO", pending: 56, delivered: 12 },
            { name: "MEI CARRO MAYCON DOUGLAS DE ASSIS MENEZES", pending: 102, delivered: 9 },
            { name: "MEI CARRO ALEXANDRE VASCONCELOS DE MORAES", pending: 53, delivered: 8 },
            { name: "TAC CARRO EMELIN SANTOS BARBOSA DE SOUZA", pending: 92, delivered: 7 },
            { name: "MEI CARRO LUCAS MACHADO THOMAS", pending: 92, delivered: 4 },
            { name: "TAC CARRO GIOVANNA STEFANY DE SOUZA COELHO LIMA", pending: 75, delivered: 3 },
            { name: "MEI CARRO UELISSON DIOGO DE MEDEIROS SILVA", pending: 143, delivered: 3 },
            { name: "MEI CARRO DOUGLAS RANIELY PASSOS GONCALVES", pending: 120, delivered: 2 },
            { name: "MEI CARRO HELDON CARLOS AZEVEDO SILVA", pending: 286, delivered: 1 },
            { name: "MEI CARRO UELTON RAMOS DA SILVA", pending: 39, delivered: 1 },
            { name: "AGR CARRO ANA LUMA CALDAS ALMEIDA", pending: 43, delivered: 0 },
            { name: "TAC CARRO SIDNEI LOPES DA SILVA JUNIOR", pending: 77, delivered: 0 },
            { name: "TAC CARRO OLAVO DE OLIVEIRA MORAIS", pending: 59, delivered: 0 },
            { name: "TAC MOTO DANILO FERREIRA DAVI", pending: 14, delivered: 0 },
            { name: "MEI CARRO JULIANE FERREIRA DA ROCHA", pending: 62, delivered: 0 },
            { name: "TAC CARRO JUNIOR DE OLIVEIRA", pending: 77, delivered: 0 },
            { name: "MEI CARRO JOAO KLEBER MARQUES NASCIMENTO", pending: 180, delivered: 0 },
            { name: "MEI CARRO KELVIN LUCAS FERREIRA DA CRUZ", pending: 123, delivered: 0 },
            { name: "MEI CARRO ALISSON MACEDO GONCALVES", pending: 78, delivered: 0 },
            { name: "ETC CARRO ANDRESSA - ADRIANA OLIVEIRA PENHA", pending: 75, delivered: 0 },
            { name: "TAC CARRO ROMULO DA SILVA MACHADO", pending: 141, delivered: 0 },
            { name: "AGR MEI CARRO JACSON HENRIQUE ROSA", pending: 113, delivered: 0 },
            { name: "MEI CARRO JOSE DELSON RIBEIRO", pending: 84, delivered: 0 },
            { name: "MEI CARRO FRANCISCO DE SOUSA FREITAS", pending: 49, delivered: 0 },
            { name: "MEI CARRO RONALD MONTEIRO SOARES", pending: 81, delivered: 0 },
            { name: "PVL -MT", pending: 116, delivered: 57 },
            { name: "MEI CARRO PVL ALEX MACEDO DA SILVA", pending: 57, delivered: 17 },
            { name: "TAC CARRO PVL PAULO DE SOUZA GONÇALVES", pending: 2, delivered: 16 },
            { name: "TAC CARRO PVL RAFAEL OLIVEIRA DE PAULA", pending: 4, delivered: 9 },
            { name: "TAC CARRO PVL FERNANDO FERREIRA DE OLIVEIRA", pending: 0, delivered: 7 },
            { name: "TAC CARRO - Rogério Silva da Rocha", pending: 43, delivered: 7 },
            { name: "MEI CARRO PVL CHRISTYAN SOBRINHO FERREIRA ABREU", pending: 7, delivered: 1 },
            { name: "MEI CARRO PVL LUCIANO DA SILVA", pending: 1, delivered: 0 },
            { name: "TAC CARRO PVL JULIANO PIRES", pending: 2, delivered: 0 }
        ]
    },
    "SMA -GO": {
        totalPending: 0,
        totalDelivered: 0,
        totalOverall: 0,
        drivers: [
        ]
    },
    "SMB -GO": {
        totalPending: 0,
        totalDelivered: 0,
        totalOverall: 0,
        drivers: [
        ]
    },
    "URC -GO": {
        totalPending: 1658,
        totalDelivered: 67,
        totalOverall: 1725,
        drivers: [
            { name: "TAC MOTO - ALESSANDRO ANTUNES DA SILVA", pending: 42, delivered: 24 },
            { name: "TAC CARRO - RODRIGO RIBEIRO SILVA LEITE", pending: 32, delivered: 16 },
            { name: "MEI CARRO - MARCIO KENNEDY RODRIGUES GOMES", pending: 58, delivered: 15 },
            { name: "MEI CARRO - LUZIA FRANCISCO OZORIO SANTOS", pending: 105, delivered: 11 },
            { name: "MEI CARRO - TASSIO VINICIUS SANTOS BRANDAO", pending: 377, delivered: 1 },
            { name: "TAC CARRO - PATRICIA MARA DE OLIVEIRA", pending: 138, delivered: 0 },
            { name: "TAC CARRO - MARCELO COSTA SILVA", pending: 97, delivered: 0 },
            { name: "TAC CARRO - DIVINO CARLOS DA SILVA", pending: 58, delivered: 0 },
            { name: "TAC CARRO - EDER RODRIGUES DA SILVA", pending: 44, delivered: 0 },
            { name: "TAC CARRO - MARCELO LISBOA PARREIRA", pending: 87, delivered: 0 },
            { name: "TAC CARRO - RODRIGO LUIZ VICENTE", pending: 34, delivered: 0 },
            { name: "TAC CARRO - ROBSON MARCIANO DA SILVA", pending: 29, delivered: 0 },
            { name: "TAC CARRO - ANTONIO CARLOS VIEIRA DA SILVA", pending: 85, delivered: 0 },
            { name: "TAC CARRO - JOAO RAMOS DE ALBUQUERQUE", pending: 129, delivered: 0 },
            { name: "MEI CARRO - CASSIO CARVALHO DA SILVA", pending: 41, delivered: 0 },
            { name: "TAC CARRO - EMERSON CAMPOS PIMENTEL", pending: 301, delivered: 0 },
            { name: "TAC CARRO - EVERLAM NOVAES DE CARVALHO", pending: 1, delivered: 0 },
            { name: "VGR 02-MT", pending: 420, delivered: 1 },
            { name: "MEI CARRO VGR RONAIR JOSE DE PAULA", pending: 25, delivered: 1 },
            { name: "MEI CARRO VGR JOZICLEI LIMA DA SILVA", pending: 164, delivered: 0 },
            { name: "TAC CARRO VGR JOZINEI SANTOS DA SILVA", pending: 54, delivered: 0 },
            { name: "TAC CARRO VGR EOCIONEY LUIS CINTRA DE OLIVEIRA", pending: 35, delivered: 0 },
            { name: "MEI CARRO VGR LEANDRO ALVES PORTO", pending: 58, delivered: 0 },
            { name: "TAC CARRO VGR MARIO GOMES DE CAMPOS", pending: 12, delivered: 0 },
            { name: "MEI CARRO VGR JOSIANE SILVA DE OLIVEIRA MONTEIRO", pending: 71, delivered: 0 },
            { name: "TAC CARRO - Patrícia da Silva Costa", pending: 1, delivered: 0 },
            { name: "VGR-MT", pending: 392, delivered: 6 },
            { name: "TAC CARRO VGR KATRYNE PEDROSO DOS SANTOS", pending: 36, delivered: 6 },
            { name: "TAC CARRO  - WILLY BISPO NASCIMENTO", pending: 27, delivered: 0 },
            { name: "TAC CARRO VGR KENIO DE ARRUDA", pending: 88, delivered: 0 },
            { name: "TAC CARRO - Valdeyse Josyhellen Marçal", pending: 14, delivered: 0 },
            { name: "TAC CARRO VGR JULIANO FERREIRA ROSA", pending: 51, delivered: 0 },
            { name: "TAC CARRO VGR  JEKSON ALBUQUERQUE SHELID", pending: 63, delivered: 0 },
            { name: "TAC MOTO VGR VIVIANE MARIA DA SILVA SANTOS", pending: 13, delivered: 0 },
            { name: "TAC CARRO VGR CLEITON CAMPOS DAVI", pending: 45, delivered: 0 },
            { name: "TAC CARRO VGR JONATHAN GERALDO DE ALCANTARA", pending: 55, delivered: 0 },
            { name: "VHL-RO", pending: 75, delivered: 11 },
            { name: "TAC CARRO ALEXANDRE FERREIRA FONSECA OSORIO", pending: 2, delivered: 10 },
            { name: "TAC CARRO MANOEL MESSIAS MENDES DA SILVA PINHEIRO", pending: 0, delivered: 1 },
            { name: "TAC CARRO DIANA LOPES DA SILVA", pending: 17, delivered: 0 },
            { name: "TAC CARRO ELAINE SOUZA GONCALVES ALVES", pending: 1, delivered: 0 },
            { name: "TAC CARRO HONORIO ROBERTO DE MOURA", pending: 18, delivered: 0 },
            { name: "TAC CARRO ANDRE APARECIDO MAQUIELE DE ANDRADE", pending: 1, delivered: 0 },
            { name: "AGR MEI CARRO RAYANA MONTEIRO GOMES", pending: 17, delivered: 0 },
            { name: "TAC CARRO AYNARA FERREIRA DA CRUZ", pending: 19, delivered: 0 },
            { name: "VLP -GO", pending: 593, delivered: 167 },
            { name: "MEI CARRO - GILSON SYLVIO DA FONSECA", pending: 46, delivered: 56 },
            { name: "MEI CARRO - HENRIQUE PORTELA DO NASCIMENTO", pending: 76, delivered: 35 },
            { name: "TAC CARRO - EDIENE GOMES FERNANDES", pending: 20, delivered: 33 },
            { name: "MEI CARRO - CONCEICAO DE MARIA SOUSA GOMES", pending: 86, delivered: 25 },
            { name: "MEI CARRO - RODRIGO ROCHA DE SOUSA BATISTA", pending: 120, delivered: 8 },
            { name: "TAC CARRO - GABRIEL NUNES BASILIO", pending: 85, delivered: 6 },
            { name: "MEI CARRO - WILLIAM DE OLIVEIRA PESSOA", pending: 160, delivered: 4 },
            { name: "Total Geral", pending: 36998, delivered: 7019 }
        ]
    }
};
